/* Q 系列（快速上手篇）自測題庫 v8 — 與 A/B 系列題庫同結構。
 * Q1 20 題、Q2 30 題、Q3 38 題，共 88 題：前幾題與影片「自測」相同，其餘取自常見錯誤、投影片新增頁與腳本練習。
 */
const subjects = {
"Q 系列 · 快速上手篇": {

"Q1：觀念篇": [
  { type:"single",
    stem:"Bulk RNA-seq 顯示腫瘤 A 的 CD8A 比腫瘤 B 高三倍。最保守的解讀？",
    stem_en:"Bulk shows CD8A three-fold higher in tumour A than B. The most conservative reading?",
    A:"A 的 T 細胞更有攻擊性", A_en:"A's T cells are more cytotoxic",
    B:"A 的 CD8 T 細胞比例可能較高，或每顆表現較高——Bulk 分不開", B_en:"A may have more CD8 T cells, or each expresses more — Bulk cannot tell",
    C:"A 對免疫治療反應較好", C_en:"A will respond better to immunotherapy",
    D:"B 的樣本純度較低", D_en:"B has lower purity",
    ans:"B",
    exp:"組成改變與內在改變在 Bulk 裡長得一樣；A、C 是過度詮釋，D 是無根據的猜測。",
    exp_en:"Composition and intrinsic change look identical in bulk; A and C over-interpret, D is a guess." },
  { type:"single",
    stem:"四位病人的 GBM 資料，UMAP 上惡性細胞分成四個群集、巨噬細胞混成一群。這代表？",
    stem_en:"Four GBM patients: malignant cells form four islands, macrophages one blended cluster. This means?",
    A:"嚴重批次效應，要整合", A_en:"Severe batch effect; integrate",
    B:"惡性細胞有四種亞型", B_en:"Four malignant subtypes",
    C:"正常現象：惡性細胞帶病人特異的 CNV，正常細胞沒有", C_en:"Expected: malignant cells carry patient-specific CNV, normal cells do not",
    D:"巨噬細胞的資料品質較差", D_en:"Macrophage data quality is poorer",
    ans:"C",
    exp:"巨噬細胞混合良好證明技術批次小；惡性細胞分成不同群集來自基因體差異，硬整合會抹掉真實生物學。",
    exp_en:"Well-blended macrophages prove technical batch is small; malignant islands come from genomic differences." },
  { type:"single",
    stem:"要證明某群細胞是惡性的，最有力的證據是？",
    stem_en:"The strongest evidence that a cluster is malignant?",
    A:"高表現 EGFR、SOX2", A_en:"High EGFR and SOX2",
    B:"整段染色體（如 chr7 增加、chr10 缺失）的表現一起偏移", B_en:"Whole chromosome arms shifting together (chr7 gain, chr10 loss)",
    C:"在 UMAP 上離免疫細胞很遠", C_en:"Far from immune cells on the UMAP",
    D:"細胞比較大、nCount 比較高", D_en:"Larger cells with higher nCount",
    ans:"B",
    exp:"marker 只說譜系、UMAP 距離無證據力、nCount 反映 RNA 量；CNV 是基因體層級證據。",
    exp_en:"Markers give lineage, UMAP distance is not evidence, nCount reflects RNA content; CNV is genome-level evidence." },
  { type:"single",
    stem:"一群 FOS、JUN、HSPA1A 高表現的細胞，同時出現在惡性、巨噬、寡樹突細胞裡各一撮。最可能是？",
    stem_en:"A FOS/JUN/HSPA1A-high group appears as a slice within malignant, macrophage and oligodendrocyte cells. Most likely?",
    A:"腫瘤誘導的共同壓力反應（真發現）", A_en:"A tumour-induced shared stress programme (real)",
    B:"解離時的立即早期反應（技術假象）", B_en:"Dissociation-induced immediate-early response (artefact)",
    C:"doublet", C_en:"Doublets",
    D:"週期 G2/M 期", D_en:"G2/M phase",
    ans:"B",
    exp:"跨型別出現、立即早期基因 + 熱休克蛋白，是解離壓力的典型長相；腫瘤組織解離時間長，訊號特別強。",
    exp_en:"Cross-type appearance of IEGs plus heat-shock genes is the classic dissociation signature; tumours dissociate slowly so it is strong." },
  { type:"single",
    stem:"10x 矩陣裡的數字是什麼？",
    stem_en:"What are the numbers in a 10x matrix?",
    A:"read 數", A_en:"Read counts",
    B:"UMI 分子數（PCR 重複已去除）", B_en:"UMI molecule counts (PCR duplicates removed)",
    C:"TPM", C_en:"TPM",
    D:"log 表現量", D_en:"log expression",
    ans:"B",
    exp:"UMI 讓同一分子的 PCR 複製只算一次；這是單細胞計數資料與 Bulk read count 的根本差別。",
    exp_en:"UMIs count each molecule once regardless of PCR copies — the fundamental difference from bulk reads." },
  { type:"single",
    stem:"預算固定，你只能二選一：多收 1 位病人，或把每個樣本從 5,000 顆細胞增加到 15,000 顆。研究問題是「核心 vs 邊緣的惡性細胞差異」。該選？",
    stem_en:"Fixed budget, one choice: one more patient, or 5,000 → 15,000 cells per sample. The question is 'core vs periphery malignant cells'. Which?",
    A:"多收病人：統計功效來自病人數，細胞數過了膝點就沒有幫助", A_en:"More patients: power comes from patients; cells past the knee do not help",
    B:"多收細胞：細胞越多 p 值越小", B_en:"More cells: more cells, smaller p",
    C:"多收細胞：才能看到稀有群", C_en:"More cells: needed to see rare populations",
    D:"兩者一樣", D_en:"No difference",
    ans:"A",
    exp:"n 是病人；惡性細胞不是稀有群，5,000 顆已足夠。C 只在研究問題是稀有群時成立。",
    exp_en:"n is patients; malignant cells are not rare, 5,000 is plenty. C holds only when the question is about a rare population." },
  { type:"single",
    stem:"FeaturePlot 上 MBP 在寡樹突細胞很亮，但每一顆細胞都有一點顏色。最可能的原因？",
    stem_en:"On a FeaturePlot MBP is bright in oligodendrocytes but every cell shows a little colour. Most likely cause?",
    A:"所有細胞都有寡樹突分化潛能", A_en:"Every cell has oligodendrocyte potential",
    B:"環境 RNA：裂解細胞的 mRNA 漂進了每顆液滴", B_en:"Ambient RNA: mRNA from lysed cells drifted into every droplet",
    C:"normalization 做錯", C_en:"Normalization error",
    D:"doublet", D_en:"Doublets",
    ans:"B",
    exp:"譜系標誌基因「到處都有一點」是環境 RNA 的典型樣子；SoupX 可估計並扣除。doublet 是少數細胞同時亮兩種 marker，不是全部細胞。",
    exp_en:"A gate gene showing a little everywhere is the signature of ambient RNA; SoupX estimates and removes it. Doublets are a few cells lighting two markers, not all cells." },
  { type:"single",
    stem:"UMAP 上兩個群集靠得很近，另一個離很遠。可以下什麼結論？",
    stem_en:"On a UMAP two clusters sit close together and a third sits far away. What follows?",
    A:"靠近的兩群在生物學上比較相似", A_en:"The two close clusters are biologically more similar",
    B:"離很遠的那一群是離群值，應該移除", B_en:"The distant cluster is an outlier and should be removed",
    C:"只能說它們在高維空間的鄰居關係被保留了；群間距離本身不可量化解讀", C_en:"Only that neighbourhood relations from high dimensions were preserved; between-cluster distance itself is not quantitatively interpretable",
    D:"靠近的兩群應該合併成一群", D_en:"The two close clusters should be merged",
    ans:"C",
    exp:"UMAP 盡力保留局部鄰居關係，不保證全域距離。要比較相似度，回 PC 空間或用相關係數、分群樹。",
    exp_en:"UMAP preserves local neighbourhoods, not global distances. To compare similarity, go back to PC space, or use correlation or a cluster tree." },
  { type:"single",
    stem:"矩陣裡某個基因在某顆細胞是 0。這個 0 代表什麼？",
    stem_en:"A gene reads 0 in one cell of the matrix. What does that zero mean?",
    A:"這顆細胞確定沒有表現這個基因", A_en:"The cell definitely does not express that gene",
    B:"可能真的沒表現，也可能有表現但沒被抓到——兩種零從數字上分不開", B_en:"It may be truly off, or expressed but not captured — the two kinds of zero are indistinguishable from the number alone",
    C:"一定是技術問題造成的漏抓", C_en:"It must be a technical dropout",
    D:"表示這顆細胞品質不好", D_en:"It means the cell is low quality",
    ans:"B",
    exp:"單細胞矩陣非常稀疏，生物性的零與捕捉不到的零混在一起。這也是為什麼判斷「有沒有表現」要看一群細胞的比例，而不是單顆。",
    exp_en:"Single-cell matrices are sparse and biological zeros are mixed with dropouts. That is why expression is judged from the fraction of cells in a group, not from one cell." },
  { type:"single",
    stem:"同樣的預算，Smart-seq2 與 10x 最主要的取捨是什麼？",
    stem_en:"On the same budget, what is the main trade-off between Smart-seq2 and 10x?",
    A:"Smart-seq2 細胞多、深度淺；10x 細胞少、深度深", A_en:"Smart-seq2 gives more cells at lower depth; 10x fewer cells at greater depth",
    B:"Smart-seq2 深度深、細胞少；10x 細胞多、每顆深度淺", B_en:"Smart-seq2 gives greater depth on fewer cells; 10x gives many cells at lower depth per cell",
    C:"兩者細胞數與深度都差不多，只差價格", C_en:"Both give similar cell numbers and depth, only price differs",
    D:"Smart-seq2 一定比較準，沒有取捨", D_en:"Smart-seq2 is simply more accurate; there is no trade-off" ,
    ans:"B",
    exp:"全長、板式的 Smart-seq2 每顆細胞讀得深（利於剪接、TCR、低表現基因），但細胞數以千計；液滴式的 10x 可以上萬顆，每顆較淺。問題決定選哪一個。",
    exp_en:"Plate-based full-length Smart-seq2 reads each cell deeply (good for splicing, TCR, low-expressed genes) but yields thousands of cells; droplet 10x yields tens of thousands at lower depth per cell. The question decides." },
  { type:"single",
    stem:"分群（FindClusters）實際上是在哪個空間裡做的？",
    stem_en:"In which space does clustering (FindClusters) actually happen?",
    A:"UMAP 的二維座標上", A_en:"On the two UMAP coordinates",
    B:"原始的基因表現矩陣上", B_en:"On the raw gene expression matrix",
    C:"前幾十個主成分構成的 PC 空間上", C_en:"In the PC space of the first few dozen principal components",
    D:"t-SNE 的二維座標上", D_en:"On the two t-SNE coordinates",
    ans:"C",
    exp:"鄰居圖建在 PC 空間，UMAP 只是把結果畫出來給人看。所以「改 UMAP 參數」不會改變分群結果，改 nPC 或 resolution 才會。",
    exp_en:"The neighbour graph is built in PC space; UMAP only draws the result. Changing UMAP parameters does not change the clusters — changing nPC or resolution does." },
  { type:"single",
    stem:"UMAP 上某一群佔的面積特別大。這代表那一群細胞數最多嗎？",
    stem_en:"One cluster covers a large area on the UMAP. Does that mean it has the most cells?",
    A:"是，面積大約正比於細胞數", A_en:"Yes, area is roughly proportional to cell number",
    B:"不一定；面積反映的是那群細胞內部的異質性與投影方式，要看數字才知道細胞數", B_en:"Not necessarily; area reflects within-cluster heterogeneity and the projection — cell numbers must be read from the table",
    C:"面積大代表那群品質比較好", C_en:"A large area means better quality",
    D:"面積大代表那群是 doublet", D_en:"A large area means the cluster is doublets",
    ans:"B",
    exp:"異質性高、狀態連續的族群會被攤得很開；緊緻的族群縮成一小團。細胞數請用 table() 或組成表，不要用眼睛量面積。",
    exp_en:"Heterogeneous, continuous populations spread out; tight populations shrink to a blob. Read counts with table() or a composition table, not by eye." },
  { type:"single",
    stem:"一篇論文宣稱找到新的細胞亞群，只給了 UMAP 上圈起來的一塊和亞群名字。你最該追問什麼？",
    stem_en:"A paper claims a new subpopulation, showing only a circled region on a UMAP and a name. What should you ask first?",
    A:"UMAP 用了什麼參數", A_en:"Which UMAP parameters were used",
    B:"支持這個名字的 marker 證據是什麼，以及在別的樣本/資料集是否重現", B_en:"What marker evidence supports the name, and whether it reproduces in other samples or datasets",
    C:"顏色為什麼選這幾種", C_en:"Why those colours were chosen",
    D:"為什麼不用 t-SNE", D_en:"Why not t-SNE",
    ans:"B",
    exp:"UMAP 上圈得出來不等於是一個生物實體。要看的是 marker 證據鏈與重現性——這也是你自己的報告會被問的問題。",
    exp_en:"Being circleable on a UMAP does not make something a biological entity. What matters is the marker evidence chain and reproducibility — the same question your own report will face." },
  { type:"single",
    stem:"GBM 常被稱為「免疫冷」腫瘤。在單細胞資料上最直接的表現是？",
    stem_en:"GBM is often called an immune-cold tumour. What is the most direct sign in single-cell data?",
    A:"T 細胞在所有細胞中的比例很低", A_en:"T cells make up a very small fraction of all cells",
    B:"惡性細胞的 CNV 訊號很弱", B_en:"The malignant CNV signal is weak",
    C:"巨噬細胞完全不存在", C_en:"Macrophages are absent",
    D:"所有免疫細胞都測不到", D_en:"No immune cells can be detected at all",
    ans:"A",
    exp:"GBM 的免疫區塊以髓系（巨噬／小膠質）為主，T 細胞往往只佔百分之幾。本課的 GBM 5k 就是這個樣子。",
    exp_en:"The immune compartment in GBM is dominated by myeloid cells; T cells are often only a few percent. The GBM 5k dataset used in this course looks exactly like that." },
  { type:"single",
    stem:"什麼情況下 bulk RNA-seq 其實就夠用，不必做單細胞？",
    stem_en:"When is bulk RNA-seq actually enough, without going single-cell?",
    A:"任何情況，bulk 比較便宜", A_en:"Always — bulk is cheaper",
    B:"你的問題是「整塊組織整體上升或下降了什麼」，而且不在意是組成改變還是細胞內在改變", B_en:"When the question is what goes up or down in the tissue as a whole, and you do not care whether that comes from composition or from within-cell change",
    C:"樣本數超過 100 的時候", C_en:"When there are more than 100 samples",
    D:"研究對象是腫瘤的時候", D_en:"Whenever the subject is a tumour",
    ans:"B",
    exp:"單細胞的價值在於把「組成改變」與「內在改變」分開。如果問題本身不需要這個區分，bulk 的樣本數與成本優勢更划算。",
    exp_en:"Single-cell earns its cost by separating compositional change from intrinsic change. If the question does not need that separation, bulk buys more samples for less." },
  { type:"single",
    stem:"實驗設計時，什麼是這個研究真正的重複（replicate）？",
    stem_en:"In the design, what counts as a true replicate?",
    A:"每一顆細胞", A_en:"Each cell",
    B:"每一位病人／每一個獨立的生物樣本", B_en:"Each patient or independent biological sample",
    C:"每一個 UMAP 上的群集", C_en:"Each cluster on the UMAP",
    D:"每一次定序 run", D_en:"Each sequencing run",
    ans:"B",
    exp:"同一位病人的幾千顆細胞不是幾千個獨立樣本。統計單位是病人——這句話會在 Q3 的差異表達再出現一次。",
    exp_en:"Thousands of cells from one patient are not thousands of independent samples. The unit is the patient — a point that returns in the Q3 differential expression section." },
  { type:"single",
    stem:"組織解離會帶來什麼系統性偏差？",
    stem_en:"What systematic bias does tissue dissociation introduce?",
    A:"沒有偏差，解離只是把細胞分開", A_en:"None; dissociation just separates cells",
    B:"脆弱或黏著性強的細胞型別容易流失，比例會偏離組織裡真實的組成", B_en:"Fragile or strongly adherent cell types are lost, so proportions drift from the true tissue composition",
    C:"所有細胞型別都等比例流失", C_en:"All cell types are lost in equal proportion",
    D:"只影響 RNA 品質，不影響組成", D_en:"It affects RNA quality only, not composition",
    ans:"B",
    exp:"神經元、脂肪細胞這類細胞常常在解離時就沒了。所以「比例」的解讀要保守，跨研究比較組成更要小心。",
    exp_en:"Neurons and adipocytes, for instance, are often lost during dissociation. Read proportions conservatively, and be especially careful comparing composition across studies." },
  { type:"single",
    stem:"UMI（unique molecular identifier）解決了什麼問題？",
    stem_en:"What problem do UMIs (unique molecular identifiers) solve?",
    A:"分辨哪一顆細胞", A_en:"Telling cells apart",
    B:"分辨「同一條 mRNA 被 PCR 放大很多次」與「本來就有很多條 mRNA」", B_en:"Distinguishing one mRNA amplified many times by PCR from many original mRNA molecules",
    C:"提高定序品質分數", C_en:"Raising sequencing quality scores",
    D:"校正批次效應", D_en:"Correcting batch effects",
    ans:"B",
    exp:"barcode 標細胞、UMI 標分子。有了 UMI 才能把 PCR 重複去掉，數字才接近真正的分子數；全長平台（如 Smart-seq2）沒有 UMI，尺度不同。",
    exp_en:"Barcodes label cells, UMIs label molecules. With UMIs, PCR duplicates can be collapsed so counts approach true molecule numbers; full-length platforms such as Smart-seq2 lack them and are on a different scale." },
  { type:"single",
    stem:"為什麼要做正規化（normalization）？",
    stem_en:"Why normalise at all?",
    A:"讓數字比較好看", A_en:"To make the numbers look nicer",
    B:"每顆細胞抓到的分子總數差很多，不校正的話比較的是深度而不是表現量", B_en:"Total molecules captured differ greatly between cells; without correction you compare depth rather than expression",
    C:"為了移除 doublet", C_en:"To remove doublets",
    D:"為了讓 p 值變小", D_en:"To make p-values smaller",
    ans:"B",
    exp:"深度差異是技術造成的。先把每顆細胞拉到可比較的尺度，後面的 HVG、PCA、分群才有意義。",
    exp_en:"Depth differences are technical. Bringing cells onto a comparable scale first is what makes HVG selection, PCA and clustering meaningful." },
  { type:"single",
    stem:"為什麼 CNV 可以用來判斷惡性，marker 卻不行？",
    stem_en:"Why can CNV establish malignancy when markers cannot?",
    A:"CNV 的 p 值比較小", A_en:"CNV gives smaller p-values",
    B:"CNV 是基因體層級的改變，正常細胞不會有；marker 只反映表現狀態，正常對應細胞也可能高表現", B_en:"CNV is a genome-level change that normal cells do not carry; markers reflect expression states that the normal counterpart cell may also show",
    C:"marker 太少了", C_en:"There are too few markers",
    D:"CNV 不需要參考細胞", D_en:"CNV needs no reference cells",
    ans:"B",
    exp:"膠質瘤惡性細胞的正常對應細胞（星狀、OPC）就在同一塊組織裡，表現高度重疊。基因體層級的證據才切得開。",
    exp_en:"The normal counterparts of glioma cells — astrocytes and OPCs — sit in the same tissue with heavily overlapping expression. Only genome-level evidence separates them." },
],

"Q2：實作篇 I": [
  { type:"single",
    stem:"GBM 資料 percent.mt 中位數 7%、median + 3×MAD = 13%。閾值該怎麼定？",
    stem_en:"GBM: median percent.mt 7%, median + 3×MAD = 13%. Where does the cutoff go?",
    A:"照慣例 5%", A_en:"The conventional 5%",
    B:"13%，並把數字與理由寫進方法段", B_en:"13%, with number and reason in the methods",
    C:"不過濾 percent.mt", C_en:"Skip the filter",
    D:"取兩者平均 9%", D_en:"Average them: 9%",
    ans:"B",
    exp:"閾值是資料的性質。5% 砍掉大半活細胞；不過濾留下垂死細胞的第二個峰；9% 沒有理由。",
    exp_en:"A threshold is a property of the data. 5% removes most live cells; no filter keeps the dying mode; 9% has no rationale." },
  { type:"single",
    stem:"某群同時高表現 SOX2 與 C1QB，doublet 工具標記其中 65% 為 doublet。該怎麼處理？",
    stem_en:"A cluster expresses SOX2 and C1QB; the doublet tool flags 65%. What now?",
    A:"有趣的新亞群，寫進結果", A_en:"Exciting new subset — report it",
    B:"整群移除並記錄理由", B_en:"Remove the whole cluster and record why",
    C:"只移除被標記的 65%", C_en:"Remove only the flagged 65%",
    D:"提高 resolution 把它再切開", D_en:"Raise resolution to split it",
    ans:"B",
    exp:"過半被標記且卡在惡性與髓系之間，整群是 doublet 產物；剩下的是工具沒抓到的。",
    exp_en:"Mostly flagged and sitting between malignant and myeloid: the whole cluster is a doublet product." },
  { type:"single",
    stem:"SingleR 把 0 號群標成 Astrocyte，marker 是 SOX2 / PTPRZ1 / EGFR。最誠實的標籤？",
    stem_en:"SingleR labels cluster 0 Astrocyte; markers SOX2 / PTPRZ1 / EGFR. The honest label?",
    A:"Astrocyte", A_en:"Astrocyte",
    B:"Malignant", B_en:"Malignant",
    C:"Glial（惡性待判定）", C_en:"Glial (malignancy undetermined)",
    D:"Neural progenitor", D_en:"Neural progenitor",
    ans:"C",
    exp:"參考集裡沒有 GBM 惡性細胞；marker 只說譜系。惡性要 CNV 證據。",
    exp_en:"No GBM malignant cells in any reference; markers only give lineage. Malignancy needs CNV." },
  { type:"single",
    stem:"nFeature_RNA 與 nCount_RNA 的 MAD 閾值為什麼要在 log10 尺度算？",
    stem_en:"Why compute MAD cutoffs for nFeature / nCount on the log10 scale?",
    A:"因為 Seurat 預設這樣做", A_en:"Because Seurat does it by default",
    B:"它們是對數常態分布，原始尺度的 MAD 會被長尾拉歪", B_en:"They are log-normal; MAD on the raw scale is distorted by the long tail",
    C:"為了讓數字比較小", C_en:"To make the numbers smaller",
    D:"percent.mt 也要在 log 尺度算", D_en:"percent.mt should also be on log scale",
    ans:"B",
    exp:"對數常態資料在 log 尺度才對稱，MAD 才有意義；percent.mt 是比例，直接算。",
    exp_en:"Log-normal data is symmetric only on the log scale; percent.mt is a proportion and is computed directly." },
  { type:"single",
    stem:"一群 MKI67、TOP2A 高的細胞自成一個群集。最合理的解讀？",
    stem_en:"An MKI67/TOP2A-high island. The most reasonable reading?",
    A:"幹細胞樣亞群", A_en:"A stem-like subpopulation",
    B:"增殖狀態，可能混了多種型別；先看 Phase 欄位", B_en:"A cycling state, possibly mixing several types; check the Phase column first",
    C:"doublet", C_en:"Doublets",
    D:"低品質細胞", D_en:"Low-quality cells",
    ans:"B",
    exp:"週期是狀態不是型別；先算週期分數才看得出來，再決定要不要 regress。",
    exp_en:"Cell cycle is a state, not a type; score it first, then decide whether to regress." },
  { type:"single",
    stem:"FindAllMarkers 給某群一個「marker」：avg_log2FC = 2.1、pct.1 = 0.28、pct.2 = 0.03、p_val_adj < 1e-100。該怎麼看？",
    stem_en:"FindAllMarkers reports a 'marker' with avg_log2FC = 2.1, pct.1 = 0.28, pct.2 = 0.03, p_val_adj < 1e-100. How to read it?",
    A:"p 值極小，是很強的 marker", A_en:"Tiny p, a very strong marker",
    B:"pct.1 只有 0.28：它描述的是群的一部分，裡面可能藏著亞群或 doublet", B_en:"pct.1 is only 0.28: it describes part of the cluster — a hidden subset or doublets",
    C:"pct.2 太低，是雜訊", C_en:"pct.2 too low, noise",
    D:"FC 不夠大", D_en:"FC not large enough",
    ans:"B",
    exp:"好的 marker 要 pct.1 > 0.5；p 值在幾千顆細胞下幾乎都極小，只當篩子。",
    exp_en:"A good marker needs pct.1 > 0.5; with thousands of cells p is always tiny and serves only as a sieve." },
  { type:"single",
    stem:"你用了 SCTransform。接下來要做 pseudobulk DE 與 inferCNV，該拿哪一層的值？",
    stem_en:"You used SCTransform. For pseudobulk DE and inferCNV, which layer do you use?",
    A:"SCT assay 的 data 層", A_en:"The SCT assay's data layer",
    B:"SCT assay 的 scale.data 層", B_en:"The SCT assay's scale.data layer",
    C:"RNA assay 的 counts 層", C_en:"The RNA assay's counts layer",
    D:"哪一層都可以", D_en:"Any layer",
    ans:"C",
    exp:"DE、CNV、pseudobulk 都需要原始整數 counts；SCT 的值只用於降維與視覺化。",
    exp_en:"DE, CNV and pseudobulk need raw integer counts; SCT values are for dimensionality reduction and visualisation." },
  { type:"single",
    stem:"你想把免疫細胞細分成小膠質、血液來源巨噬細胞、CD4/CD8 T。最正確的做法？",
    stem_en:"You want to split immune cells into microglia, blood-derived macrophages and CD4/CD8 T. The correct approach?",
    A:"在全體的 UMAP 上把免疫類群用更高的 resolution 再切", A_en:"Re-cluster the immune major group at higher resolution on the global UMAP",
    B:"subset 出免疫細胞，重算 HVG、PCA、分群、UMAP，再用免疫 marker 面板註釋", B_en:"Subset immune cells, recompute HVGs, PCA, clusters and UMAP, then annotate with an immune panel",
    C:"直接用 SingleR 的 label.fine", C_en:"Just use SingleR's label.fine",
    D:"用 FeaturePlot 手動圈", D_en:"Circle them manually on a FeaturePlot",
    ans:"B",
    exp:"全體的 HVG 與前幾個 PC 被「惡性 vs 免疫」佔滿，亞群訊號排不進去；subset 後一定重算。SingleR 可當第二獨立證據但不是答案。",
    exp_en:"Global HVGs and top PCs are dominated by malignant-vs-immune; subset signal is excluded. Always recompute after subsetting. SingleR is a second line of evidence, not the answer." },
  { type:"single",
    stem:"一群細胞只有 MKI67、TOP2A 顯著，其他 marker 跟旁邊的巨噬細胞一樣，Phase 幾乎全是 S/G2M。該怎麼註釋？",
    stem_en:"A cluster is significant only for MKI67 and TOP2A, otherwise matches neighbouring macrophages, and is nearly all S/G2M. How to annotate?",
    A:"新型別：腫瘤幹細胞", A_en:"A new type: tumour stem cells",
    B:"Cycling macrophage：狀態，併回巨噬細胞並在第三層標註", B_en:"Cycling macrophage: a state, merged back into macrophages and noted at level 3",
    C:"移除，因為是 doublet", C_en:"Remove as doublets",
    D:"回歸週期後重新命名", D_en:"Regress the cycle and rename",
    ans:"B",
    exp:"增殖是狀態不是型別；命名用「形容詞 + 型別」，存在 celltype_l3。",
    exp_en:"Proliferation is a state, not a type; name it 'adjective + type' and store at celltype_l3." },
  { type:"single",
    stem:"clustree 顯示 res 0.4、0.5、0.6 三層結構一致，0.8 以後細胞開始來回換群。該用哪一個？",
    stem_en:"clustree shows res 0.4, 0.5 and 0.6 agreeing; cells start swapping from 0.8 up. Which do you take?",
    A:"0.8，群比較多比較細", A_en:"0.8 — more clusters, finer detail",
    B:"0.5，穩定層的中間值，再用 marker 檢查每一刀", B_en:"0.5 — the middle of the stable band, then check each cut with markers",
    C:"1.2，先切細再合併", C_en:"1.2 — over-split first, merge later",
    D:"都跑，挑結果最好看的", D_en:"Run them all and keep whichever looks best",
    ans:"B",
    exp:"穩定層代表這幾刀換參數也不會變，取中間值最保險。挑「最好看的」等於用結果決定方法。",
    exp_en:"A stable band means those cuts survive a parameter change; the middle is the safest pick. Choosing the prettiest result lets the answer decide the method." },
  { type:"single",
    stem:"某個 marker 的 padj = 1e-40，但 pct.1 = 0.22、pct.2 = 0.19。這個 marker 能用嗎？",
    stem_en:"A marker has padj = 1e-40 but pct.1 = 0.22 and pct.2 = 0.19. Usable?",
    A:"能，padj 這麼小一定是真的", A_en:"Yes — a padj that small must be real",
    B:"不能，群內外幾乎一樣多細胞在表現", B_en:"No — nearly the same fraction expresses it inside and outside",
    C:"要看 avg_log2FC 是正是負", C_en:"Depends on the sign of avg_log2FC",
    D:"要看該群有幾顆細胞", D_en:"Depends on the cluster size",
    ans:"B",
    exp:"cell-level 檢定把細胞當樣本，幾千顆細胞下 padj 天生極小；pct 差 0.03 代表不具區辨力。",
    exp_en:"A cell-level test treats cells as samples, so padj is tiny by construction; a 0.03 gap in pct means no discrimination." },
  { type:"single",
    stem:"有一群細胞四個譜系標誌基因（PTPRC、SOX2、MBP、PECAM1）都不亮。下一步？",
    stem_en:"One cluster lights up none of the four gate genes (PTPRC, SOX2, MBP, PECAM1). Next step?",
    A:"標成 unknown 就好", A_en:"Label it unknown and move on",
    B:"刪掉，認不出來就不要", B_en:"Delete it — unidentifiable",
    C:"先看它自己的 top marker 與 QC，必要時 subset 重跑", C_en:"Read its own top markers and QC first; subset-rerun if needed",
    D:"把 resolution 調高再分一次", D_en:"Raise the resolution and split again",
    ans:"C",
    exp:"gate 基因只涵蓋四大類群，周細胞、纖維母本來就會落在外面；低品質細胞同樣什麼都不亮，所以 QC 也要看。",
    exp_en:"The gate genes only cover the four major groups, so pericytes and fibroblasts fall outside; low-quality cells also light up nothing, so check QC too." },
  { type:"single",
    stem:"你懷疑資料有環境 RNA（ambient RNA）。跑完 SoupX 校正後，哪一種結果支持「這是環境 RNA」而不是生物學？",
    stem_en:"You suspect ambient RNA. After SoupX correction, which outcome supports ambient RNA rather than biology?",
    A:"訊號整片變淡、各群一起下降", A_en:"The signal fades across the board, dropping in every cluster together",
    B:"訊號只在一兩個亞群還在，其他群消失", B_en:"The signal survives in one or two subpopulations and disappears elsewhere",
    C:"訊號完全沒變", C_en:"The signal does not change at all",
    D:"細胞數變少了", D_en:"The cell count drops",
    ans:"A",
    exp:"環境 RNA 是均勻灑在所有液滴上的背景，校正後會整片消失；真的生物訊號會集中在特定亞群並有自己的專屬 marker 撐著。",
    exp_en:"Ambient RNA is background sprinkled evenly across droplets, so it fades everywhere after correction; a real biological signal concentrates in specific subpopulations backed by their own markers." },
  { type:"single",
    stem:"CellRanger 的 raw 與 filtered 矩陣，什麼時候會用到 raw？",
    stem_en:"CellRanger outputs raw and filtered matrices. When do you need raw?",
    A:"任何時候都用 raw，資訊比較完整", A_en:"Always use raw — it has more information",
    B:"估計環境 RNA 時（空液滴正是背景的來源）", B_en:"When estimating ambient RNA — empty droplets are exactly the background source",
    C:"分群時用 raw 比較不會漏掉細胞", C_en:"For clustering, so no cells are missed",
    D:"raw 只是備份，永遠用不到", D_en:"Raw is only a backup and is never needed",
    ans:"B",
    exp:"filtered 已經做過 cell calling，是分析的起點；raw 含幾十萬個空液滴，是 SoupX 這類方法估背景的原料，不要拿去做 QC 或分群。",
    exp_en:"Filtered has already been through cell calling and is the analysis starting point; raw holds hundreds of thousands of empty droplets and feeds ambient-RNA estimation — it is not for QC or clustering." },
  { type:"single",
    stem:"該不該把細胞週期分數 regress 掉？",
    stem_en:"Should the cell-cycle score be regressed out?",
    A:"一律要 regress，週期是技術雜訊", A_en:"Always regress it; the cycle is technical noise",
    B:"一律不要 regress", B_en:"Never regress it",
    C:"看問題：週期會蓋掉你要看的結構就 regress；增殖本身是研究對象就不要", C_en:"It depends: regress it when the cycle masks the structure you care about; keep it when proliferation is itself the question",
    D:"只有 10x 資料需要 regress", D_en:"Only 10x data needs it",
    ans:"C",
    exp:"腫瘤裡「哪一種狀態在增殖」常常就是重點，regress 掉等於把答案丟了。做與不做都要寫下理由，並附上兩版的圖。",
    exp_en:"In tumours, which state is proliferating is often the point, and regressing it throws the answer away. Either way, record the reason and show both versions." },
  { type:"single",
    stem:"nPC 選得太少，最直接的後果是？",
    stem_en:"What is the most direct consequence of choosing too few PCs?",
    A:"計算會變慢", A_en:"Computation gets slower",
    B:"細胞數會減少", B_en:"Cells are lost",
    C:"稀有或細微的族群被壓掉，該分開的群分不出來", C_en:"Rare or subtle populations get flattened and fail to separate",
    D:"marker 的 p 值會變大", D_en:"Marker p-values get larger",
    ans:"C",
    exp:"PC 取太少會丟掉承載稀有族群的變異方向；取太多則把雜訊也帶進鄰居圖。ElbowPlot 加上「拐點在哪」的理由，比抄一個數字可靠。",
    exp_en:"Too few PCs discards the variation that carries rare populations; too many drags noise into the neighbour graph. An ElbowPlot plus a stated reason beats copying a number." },
  { type:"single",
    stem:"膠質細胞群在 Neftel 的 AC-like 分數很高。可以據此判定它們是惡性的嗎？",
    stem_en:"A glial cluster scores high on the Neftel AC-like module. Does that make it malignant?",
    A:"可以，AC-like 是惡性狀態", A_en:"Yes, AC-like is a malignant state",
    B:"不行；正常星狀細胞也會拿高分，四狀態是在已確認惡性的細胞裡定義的", B_en:"No; normal astrocytes score high too — the four states were defined within cells already known to be malignant",
    C:"可以，只要分數超過 0.5", C_en:"Yes, as long as the score exceeds 0.5",
    D:"要看 UMAP 位置才知道", D_en:"It depends on the position on the UMAP",
    ans:"B",
    exp:"狀態分數只說「偏向哪一種狀態」，不能反推惡性。惡性判定要靠 CNV 這類基因體層級證據，這也是 Q3 的主題。",
    exp_en:"A state score says which state a cell leans towards; it cannot establish malignancy. That needs genome-level evidence such as CNV — the subject of Q3." },
  { type:"single",
    stem:"resolution 從 0.5 一路調到 2.0，群越切越多。這樣做的風險是？",
    stem_en:"Pushing resolution from 0.5 to 2.0 keeps splitting clusters. What is the risk?",
    A:"沒有風險，越細越好", A_en:"No risk — finer is always better",
    B:"會切出無法用 marker 支持的群，把雜訊或連續狀態當成獨立族群", B_en:"You create clusters no marker can support, treating noise or a continuum as separate populations",
    C:"細胞會被重複計算", C_en:"Cells get counted twice",
    D:"UMAP 會壞掉", D_en:"The UMAP breaks",
    ans:"B",
    exp:"分幾群不是越多越好，而是「每一群都說得出 marker 證據」。用 clustree 看結構在哪一層開始不穩，並回頭檢查每群的 marker。",
    exp_en:"The right number of clusters is not the largest one, but the one where every cluster has marker evidence. Use clustree to see where structure becomes unstable, then check markers per cluster." },
  { type:"single",
    stem:"挑 marker 時只看 p_val_adj 排序，最容易犯什麼錯？",
    stem_en:"Ranking markers by p_val_adj alone — what mistake does that invite?",
    A:"漏掉高表現的基因", A_en:"Missing highly expressed genes",
    B:"把「幾乎每群都有、只是這群略高」的基因當成專屬 marker", B_en:"Treating genes present in nearly every cluster but slightly higher here as exclusive markers",
    C:"p 值會算錯", C_en:"The p-values come out wrong",
    D:"marker 數量會太少", D_en:"Too few markers are returned",
    ans:"B",
    exp:"細胞數一多，微小差異也會有極小的 p 值。要一起看 pct.1 與 pct.2 的落差和 avg_log2FC——專屬性才是 marker 的重點。",
    exp_en:"With many cells, tiny differences get tiny p-values. Read pct.1 versus pct.2 and avg_log2FC together — exclusivity is what makes a marker." },
  { type:"single",
    stem:"直接把別人論文的 marker 面板抄過來註釋自己的資料，最可能出什麼問題？",
    stem_en:"Copying a marker panel straight from another paper — what typically goes wrong?",
    A:"完全不會有問題，marker 是通用的", A_en:"Nothing; markers are universal",
    B:"組織、物種、平台不同會讓部分 marker 失效或改變含義，且對方沒有的型別你就看不到", B_en:"Different tissue, species or platform can invalidate or shift markers, and any type absent from their panel stays invisible to you",
    C:"會讓細胞數變少", C_en:"It reduces the cell count",
    D:"只會影響圖的顏色", D_en:"It only affects plot colours",
    ans:"B",
    exp:"面板是起點不是答案。抄過來要逐個驗證在自己資料上的表現，並補上這份組織該有、對方卻沒列的型別。",
    exp_en:"A panel is a starting point, not an answer. Verify each gene on your own data and add the types your tissue should contain that their panel omits." },
  { type:"single",
    stem:"CreateSeuratObject 的 min.cells 與 min.features 在做什麼？",
    stem_en:"What do min.cells and min.features do in CreateSeuratObject?",
    A:"min.cells 濾細胞、min.features 濾基因", A_en:"min.cells filters cells and min.features filters genes",
    B:"min.cells 濾掉幾乎沒被偵測到的基因、min.features 濾掉抓到基因數過少的細胞", B_en:"min.cells drops genes detected in almost no cells; min.features drops cells with too few detected genes",
    C:"兩個都是濾細胞，只是門檻不同", C_en:"Both filter cells, just at different thresholds",
    D:"兩個都只影響計算速度，不影響結果", D_en:"Both only affect speed, not results",
    ans:"B",
    exp:"這是建物件時最粗的一層過濾。Smart-seq2 這種深度高的資料，min.features 會設得比液滴資料高（本課用 500）。",
    exp_en:"This is the coarsest filter, applied when the object is built. For deep data such as Smart-seq2, min.features is set higher than for droplet data (500 in this course)." },
  { type:"single",
    stem:"HVG 從 2000 改成 5000，最可能發生什麼？",
    stem_en:"Raising the number of HVGs from 2000 to 5000 — what typically happens?",
    A:"一定會找到更多稀有族群", A_en:"More rare populations are always found",
    B:"納入更多低變異基因，訊噪比下降，前幾個 PC 的結構可能被稀釋", B_en:"More low-variance genes enter, signal-to-noise drops, and the structure in the leading PCs may be diluted",
    C:"分群結果不會有任何改變", C_en:"Clustering does not change at all",
    D:"細胞數會增加", D_en:"The cell count increases",
    ans:"B",
    exp:"HVG 數量是一個假設：你認為多少個基因承載了生物變異。換一個數字重跑、看 elbow 前段 PC 穩不穩，比抄預設值可靠。",
    exp_en:"The HVG count is a hypothesis about how many genes carry the biological variation. Rerun with another value and check whether the leading PCs stay stable, rather than copying the default." },
  { type:"single",
    stem:"percent.mt 偏高的細胞，一定要濾掉嗎？",
    stem_en:"Must cells with high percent.mt always be removed?",
    A:"一定要，粒線體高就是死細胞", A_en:"Yes — high mitochondrial content always means a dying cell",
    B:"不一定；心肌、腎小管這類高耗能組織本來就高，腫瘤檢體的分布也普遍右移，要看這份資料自己的分布", B_en:"Not necessarily; high-energy tissues such as heart or kidney tubule are naturally high, and tumour samples shift right — judge from this dataset's own distribution",
    C:"只要低於 5% 就好", C_en:"Anything under 5% is fine",
    D:"跟組織無關，門檻固定", D_en:"Tissue is irrelevant; the threshold is fixed",
    ans:"B",
    exp:"5% 或 10% 都只是別人資料上的數字。畫出自己的分布、用 MAD 之類的動態方式訂閾值，並把放寬或收緊的理由寫下來。",
    exp_en:"5% or 10% are numbers from someone else's data. Plot your own distribution, set the threshold dynamically (for example with MAD), and record why you loosened or tightened it." },
  { type:"single",
    stem:"DoubletFinder 需要一個「預期 doublet 比例」。這個數字從哪裡來？",
    stem_en:"DoubletFinder needs an expected doublet rate. Where does that number come from?",
    A:"固定用 10%", A_en:"Always use 10%",
    B:"依平台的上樣細胞數估——液滴平台的 doublet 率隨上樣量上升，官方有對照表", B_en:"From the loaded cell number for that platform — droplet doublet rates rise with loading, and the vendor publishes a table",
    C:"由演算法自動偵測，不用給", C_en:"The algorithm detects it automatically; no input needed",
    D:"看 UMAP 上有幾群怪怪的", D_en:"By counting odd-looking clusters on the UMAP",
    ans:"B",
    exp:"上樣越多、doublet 越多。這個參數給錯，抓出來的 doublet 數量就跟著錯——所以它也是要寫進「數字、理由、紀錄」的參數之一。",
    exp_en:"More cells loaded means more doublets. Get this parameter wrong and the number of calls is wrong too — so it belongs in the number-reason-record log like any other." },
  { type:"single",
    stem:"某一群同時高表現 T 細胞與髓系的 marker。最不該做的處理是？",
    stem_en:"A cluster co-expresses T-cell and myeloid markers. What should you not do?",
    A:"檢查 doublet 分數與 nFeature 是不是偏高", A_en:"Check whether doublet scores and nFeature run high",
    B:"直接命名成「T-myeloid 雙功能新亞群」寫進結果", B_en:"Name it a novel bifunctional T-myeloid subpopulation and write it up",
    C:"提高 resolution 看它會不會拆開", C_en:"Raise the resolution to see whether it splits",
    D:"檢查是不是環境 RNA 造成的微量表現", D_en:"Check whether ambient RNA explains the low-level expression",
    ans:"B",
    exp:"共表現最常見的解釋是 doublet 或環境 RNA，新亞群是最後才輪到的解釋。排除完技術原因、而且有獨立證據，才談得上新發現。",
    exp_en:"Co-expression is most often doublets or ambient RNA; a novel subpopulation is the last explanation to reach for. Rule out the technical causes and find independent evidence first." },
  { type:"single",
    stem:"三層命名規範 celltype_l1 / l2 / l3 分別放什麼？",
    stem_en:"In the three-level naming scheme celltype_l1 / l2 / l3, what goes where?",
    A:"l1 狀態、l2 型別、l3 主要類群", A_en:"l1 state, l2 type, l3 major compartment",
    B:"l1 主要類群、l2 型別、l3 狀態或亞群", B_en:"l1 major compartment, l2 type, l3 state or subpopulation",
    C:"三層都一樣，只是備份", C_en:"All three are the same, kept as backups",
    D:"l1 是英文、l2 是中文、l3 是縮寫", D_en:"l1 English, l2 Chinese, l3 abbreviation",
    ans:"B",
    exp:"例如 Immune → Macrophage → Cycling TAM。分層的好處是圖表可以按需要挑一層畫，也讓「我對這一層有把握、那一層還沒」說得清楚。",
    exp_en:"For example Immune to Macrophage to Cycling TAM. Layering lets figures pick the level they need, and makes it explicit which level you are confident about." },
  { type:"single",
    stem:"某群的輪廓係數（silhouette）只有 0.16，明顯低於其他群。該怎麼處理？",
    stem_en:"One cluster has a silhouette width of only 0.16, clearly below the others. What now?",
    A:"直接與最相近的群合併", A_en:"Merge it with the nearest cluster",
    B:"先看它有沒有自己的 marker：低分可能只是因為細胞少、或它本來就貼著另一群，有 marker 就留著", B_en:"First check whether it has its own markers: a low score can simply mean few cells or a neighbouring population — keep it if the markers hold",
    C:"直接刪掉", C_en:"Delete it",
    D:"提高 resolution 讓它變高", D_en:"Raise the resolution until the score improves",
    ans:"B",
    exp:"輪廓係數是提示不是判決。本課的血管／纖維母細胞群只有一百多顆又貼著血管，分數低卻有明確 marker——低分不等於該併。",
    exp_en:"Silhouette is a hint, not a verdict. The vascular/fibroblast cluster in this course has only a hundred-odd cells hugging the vasculature: a low score but clear markers — low does not mean merge." },
  { type:"single",
    stem:"重跑同一份腳本，分群結果卻跟上次不一樣。最可能的原因？",
    stem_en:"Rerunning the same script gives different clusters. Most likely cause?",
    A:"資料壞了", A_en:"The data is corrupted",
    B:"沒有設 set.seed，或改動了上游參數（HVG、nPC、resolution）", B_en:"No set.seed, or an upstream parameter changed (HVG, nPC, resolution)",
    C:"Seurat 版本每次都不同", C_en:"Seurat differs on every run",
    D:"UMAP 本來就每次不同，分群也跟著變", D_en:"UMAP differs every time, so clusters follow",
    ans:"B",
    exp:"UMAP 與 Louvain 都用到隨機初始化。`set.seed(1234)` 之外，也要把套件版本記進 sessionInfo——可重現是交付的一部分。",
    exp_en:"Both UMAP and Louvain use random initialisation. Beyond set.seed(1234), record package versions with sessionInfo — reproducibility is part of the deliverable." },
  { type:"single",
    stem:"方法段（Methods）寫到什麼程度才算夠？",
    stem_en:"How detailed should the Methods section be?",
    A:"寫出用了 Seurat 就好", A_en:"Saying Seurat was used is enough",
    B:"另一個受過同樣訓練的人，不用問你任何問題就能重現你的結果", B_en:"Another similarly trained person can reproduce your result without asking you anything",
    C:"越短越好，細節放補充資料", C_en:"As short as possible, with details in the supplement",
    D:"只要列出所有套件的版本號", D_en:"Listing all package versions is enough",
    ans:"B",
    exp:"這是最實用的檢驗標準：把方法段拿給同學看，他問你的每一個問題，都是你漏寫的東西。",
    exp_en:"That is the practical test: hand the Methods to a colleague, and every question they ask marks something you left out." },
  { type:"single",
    stem:"註釋完成後，哪一種交付內容最能讓別人相信你的標籤？",
    stem_en:"After annotation, what best convinces a reader of your labels?",
    A:"一張漂亮的 UMAP", A_en:"A beautiful UMAP",
    B:"每一群的 marker 證據（DotPlot／熱圖）＋ 每群的 QC 表 ＋ 說明哪些群仍不確定", B_en:"Marker evidence per cluster (DotPlot or heatmap), a per-cluster QC table, and an honest note on which clusters remain uncertain",
    C:"細胞數最多的那幾群的名字", C_en:"The names of the largest clusters",
    D:"SingleR 的分數表", D_en:"The SingleR score table",
    ans:"B",
    exp:"「哪幾群我還不確定」這句話反而最能建立信任。留著 (undetermined) 比硬給名字誠實，也替後面的惡性判定留下空間。",
    exp_en:"Stating which clusters remain uncertain is what builds trust. Leaving them as undetermined is more honest than forcing a name, and leaves room for the malignancy call later." },
],

"Q3：實作篇 II": [
  { type:"single",
    stem:"跑 inferCNV 時，哪一組最適合當參考細胞？",
    stem_en:"Safest inferCNV reference?",
    A:"表現 GFAP 的星狀細胞群", A_en:"The GFAP-expressing astrocyte cluster",
    B:"免疫細胞與寡樹突細胞", B_en:"Immune cells and oligodendrocytes",
    C:"UMAP 上離惡性細胞最遠的群", C_en:"Whatever is farthest from malignant cells on the UMAP",
    D:"所有非惡性標籤的細胞", D_en:"All cells not labelled malignant",
    ans:"B",
    exp:"參考組必須確定沒有 CNV；星狀細胞可能是 AC 樣惡性細胞；UMAP 距離不是證據。",
    exp_en:"References must be CNV-free; astrocytes may be AC-like malignant cells; UMAP distance is not evidence." },
  { type:"single",
    stem:"Harmony 之後惡性細胞混成一團。這代表？",
    stem_en:"After Harmony, malignant cells are one blended cluster. This means?",
    A:"整合成功，直接做下游", A_en:"Integration worked; proceed",
    B:"整合把病人特異的 CNV 生物學修掉了；惡性分析回未整合空間", B_en:"Patient-specific CNV biology was erased; analyse malignant cells in the unintegrated space",
    C:"四位病人是同一亞型", C_en:"The four patients share a subtype",
    D:"要提高 theta 再整合一次", D_en:"Raise theta and integrate again",
    ans:"B",
    exp:"惡性按病人分成不同群集是基因體差異；整合空間只拿來註釋正常細胞。",
    exp_en:"Malignant patient islands are genomic; the integrated space is for annotating normal cells only." },
  { type:"single",
    stem:"核心 vs 邊緣的惡性細胞 DE，DESeq2 的 design？",
    stem_en:"Design for core vs periphery malignant DE?",
    A:"~ tissue", A_en:"~ tissue",
    B:"~ patient + tissue", B_en:"~ patient + tissue",
    C:"~ tissue + n_cells", C_en:"~ tissue + n_cells",
    D:"~ tissue * patient", D_en:"~ tissue * patient",
    ans:"B",
    exp:"配對設計先吸掉病人差異；細胞數已由 pseudobulk 處理；交互作用項在 n = 4 時無法估計。",
    exp_en:"Paired design absorbs patient first; cell number is handled by pseudobulk; an interaction cannot be estimated at n = 4." },
  { type:"single",
    stem:"pseudobulk 只取惡性細胞而不是所有細胞，是為了？",
    stem_en:"Why pseudobulk malignant cells only, not all cells?",
    A:"減少計算量", A_en:"To save compute",
    B:"否則比的是組成（邊緣的正常腦細胞較多），不是惡性細胞的變化", B_en:"Otherwise you compare composition (more normal brain at the periphery), not malignant-cell change",
    C:"DESeq2 只接受單一型別", C_en:"DESeq2 accepts one type only",
    D:"惡性細胞的 counts 比較大", D_en:"Malignant cells have larger counts",
    ans:"B",
    exp:"不同部位的型別組成不同；混合加總後的差異大半來自組成，MBP、PLP1 會衝到前面。",
    exp_en:"Composition differs by site; pooled differences are mostly composition — MBP and PLP1 rise to the top." },
  { type:"single",
    stem:"「邊緣的惡性細胞比例從 65% 降到 20%」，四位病人各一對樣本。該用什麼檢定？",
    stem_en:"'Malignant fraction drops from 65% to 20% at the periphery', four paired samples. Which test?",
    A:"對比例做配對 t-test", A_en:"Paired t-test on the proportions",
    B:"propeller（logit 轉換 + limma，樣本為單位、配對）", B_en:"propeller (logit + limma, sample-level, paired)",
    C:"對細胞做卡方檢定", C_en:"Chi-square on cells",
    D:"不用檢定，差異很明顯", D_en:"No test needed; the difference is obvious",
    ans:"B",
    exp:"比例是組成資料且單位是樣本；卡方把細胞當獨立觀察值（pseudoreplication）。",
    exp_en:"Proportions are compositional and the unit is the sample; chi-square treats cells as independent (pseudoreplication)." },
  { type:"single",
    stem:"Harmony 整合後，免疫細胞的 LISI 中位數約 3.6、惡性細胞約 1.2（四位病人）。這代表？",
    stem_en:"After Harmony, median LISI ≈ 3.6 for immune cells and ≈ 1.2 for malignant cells (four patients). This means?",
    A:"整合失敗，惡性細胞沒混好，要調高 theta", A_en:"Integration failed for malignant cells; raise theta",
    B:"正確：正常細胞跨病人混合、惡性細胞保留病人差異", B_en:"Correct: normal cells blend across patients, malignant cells keep patient differences",
    C:"免疫細胞被過度修正", C_en:"Immune cells are over-corrected",
    D:"LISI 不能用在 Harmony", D_en:"LISI does not apply to Harmony",
    ans:"B",
    exp:"免疫細胞 LISI 接近病人數 = 整合成功；惡性細胞接近 1 = 病人特異 CNV 被保住，正是我們要的。",
    exp_en:"Immune LISI near the patient count = integration worked; malignant near 1 = patient-specific CNV preserved, exactly as intended." },
  { type:"single",
    stem:"把 Smart-seq2 的 inferCNV 參數（cutoff = 1）直接用在 10x 資料上，最可能的結果？",
    stem_en:"Using the Smart-seq2 inferCNV cutoff (= 1) directly on 10x data most likely gives?",
    A:"熱圖幾乎空白：多數基因因平均表現低於 cutoff 被丟掉", A_en:"A nearly blank heatmap: most genes fall below the cutoff and are dropped",
    B:"結果更準確", B_en:"More accurate results",
    C:"跑得更慢", C_en:"Slower run",
    D:"沒有差別", D_en:"No difference",
    ans:"A",
    exp:"10x 每顆細胞分子數少一個量級，cutoff 應為 0.1；用 1 會丟掉幾乎所有基因。",
    exp_en:"10x has an order of magnitude fewer molecules per cell; the cutoff should be 0.1. Using 1 drops nearly every gene." },
  { type:"single",
    stem:"CellChat 的 netVisual_circle 顯示巨噬細胞 → 惡性細胞的邊「互動數」最多，但「互動強度」最粗的是惡性 → 內皮。該先追哪一條？",
    stem_en:"CellChat's netVisual_circle shows the most interaction pairs for macrophage → malignant, but the thickest weight for malignant → endothelial. Which to chase first?",
    A:"互動數最多的那條", A_en:"The one with the most pairs",
    B:"強度最粗的那條，再回頭看它由幾對 L–R 組成", B_en:"The thickest weight, then check how many L–R pairs compose it",
    C:"兩條一樣重要", C_en:"Both equally",
    D:"看 p 值最小的", D_en:"The smallest p value",
    ans:"B",
    exp:"對數多不代表強；先看 weight 找主軸，再回 count 圖與 contribution 看組成。",
    exp_en:"Many pairs ≠ strong; find the main axis by weight, then return to counts and contribution for composition." },
  { type:"single",
    stem:"你把四位病人的核心樣本合併成一個 Seurat 物件跑 CellChat，得到很多顯著的配體受體對。最大的問題是？",
    stem_en:"You merged four patients' core samples into one Seurat object and ran CellChat, getting many significant pairs. The biggest problem?",
    A:"細胞太多跑太慢", A_en:"Too many cells, too slow",
    B:"配體與受體可能來自不同病人的細胞——它們不可能真的對話；要每個樣本分開跑", B_en:"Ligand and receptor may come from different patients' cells — they cannot actually talk; run per sample",
    C:"應該用 counts 層", C_en:"Should have used the counts layer",
    D:"沒有問題", D_en:"No problem",
    ans:"B",
    exp:"通訊只能發生在同一個樣本內；合併跑會製造假的配對。每樣本各跑一次，再比較四位病人一致的路徑。",
    exp_en:"Communication happens only within a sample; pooling fabricates pairs. Run per sample, then compare pathways consistent across patients." },
  { type:"single",
    stem:"你的 pseudobulk 火山圖所有點擠成一根直柱，log2FC 幾乎都是 0.2 左右，但 padj 很小。最可能的原因是？",
    stem_en:"Your pseudobulk volcano is a single vertical bar: nearly every log2FC sits near 0.2, yet padj is tiny. Most likely cause?",
    A:"DESeq2 沒收斂", A_en:"DESeq2 failed to converge",
    B:"樣本只有 8 個時 apeglm 的先驗太強，把幾乎所有 LFC 壓成同一值；火山圖改用未收縮 LFC，效應量改用 ashr", B_en:"With 8 samples the apeglm prior dominates and squeezes nearly every LFC to one value; plot the raw LFC and report ashr",
    C:"基因太多，應該先篩到 2,000 個", C_en:"Too many genes; filter to 2,000 first",
    D:"應該用 cell-level Wilcoxon", D_en:"Use cell-level Wilcoxon instead",
    ans:"B",
    exp:"收縮太強是小 n 的典型症狀。GSEA 的排序也會因此全是同分而跑不完——改用 Wald stat 排序。",
    exp_en:"Over-shrinkage is the classic small-n symptom. GSEA ranks become all ties and never finish — rank by the Wald stat instead." },
  { type:"single",
    stem:"用 clusterProfiler 做 GO ORA 時，universe 留空與設成「被檢定的基因」相比，結果通常會？",
    stem_en:"In clusterProfiler GO ORA, leaving universe empty versus setting it to the tested genes usually gives?",
    A:"完全一樣", A_en:"Identical results",
    B:"顯著詞條變少", B_en:"Fewer significant terms",
    C:"顯著詞條大幅變多，多數是假的——因為單細胞只測到一萬多個基因，用全基因組當背景每個詞條都膨脹", C_en:"Many more significant terms, mostly spurious — single cell detects ten-odd thousand genes, and a whole-genome background inflates every term",
    D:"只影響 KEGG 不影響 GO", D_en:"Affects KEGG only, not GO",
    ans:"C",
    exp:"背景必須是進了 DESeq2 的那些基因。GSEA 沒有這個坑，因為它的背景自動是排序清單本身。",
    exp_en:"The background must be the genes that entered DESeq2. GSEA avoids this trap since its background is the ranked list itself." },
  { type:"single",
    stem:"整合後正常細胞四位病人混得很好，惡性細胞也混在一起了。最合理的判斷？",
    stem_en:"After integration normal cells from all four patients mix well — and so do malignant cells. Reasonable read?",
    A:"整合成功，可以往下走", A_en:"Integration succeeded; carry on",
    B:"很可能校正過頭，用負對照與已知 marker 回頭檢查", B_en:"Likely over-corrected; recheck with the negative control and known markers",
    C:"惡性細胞本來就該混，都是 GBM", C_en:"Malignant cells should mix — they are all GBM",
    D:"要再加一輪 Harmony", D_en:"Run another round of Harmony",
    ans:"B",
    exp:"惡性細胞帶各自的 CNV，跨病人本來就會有相當一部分分開；完全混在一起通常是校正壓掉了真訊號。",
    exp_en:"Malignant cells carry their own CNVs and a substantial part separates by patient; complete blending usually means the correction removed real signal." },
  { type:"single",
    stem:"某型別只有 2 位病人配得成對，DESeq2 給出 300 個 padj < 0.05 的基因。可以報嗎？",
    stem_en:"A cell type has only 2 usable patient pairs and DESeq2 returns 300 genes at padj < 0.05. Report them?",
    A:"可以，padj 已經校正過", A_en:"Yes — padj is already corrected",
    B:"不行，先報 n，清單只能當候選", B_en:"No — report n first; the list is candidates at most",
    C:"把門檻改嚴就可以報", C_en:"Tighten the threshold, then report",
    D:"改用 cell-level 檢定重跑", D_en:"Rerun with a cell-level test instead",
    ans:"B",
    exp:"n = 2 的配對設計幾乎沒有功效，三百個顯著多半代表離散度估不準；改門檻不會增加功效。",
    exp_en:"A paired design at n = 2 has almost no power; three hundred hits usually means an unreliable dispersion estimate, and a tighter threshold adds none." },
  { type:"single",
    stem:"同一份 DE 結果，ORA 沒有顯著詞條、GSEA 有五條 padj < 0.05。怎麼看？",
    stem_en:"On one DE result ORA returns nothing significant while GSEA returns five at padj < 0.05. How to read it?",
    A:"矛盾，兩個都不能信", A_en:"They contradict; trust neither",
    B:"ORA 對，GSEA 太寬鬆", B_en:"ORA is right; GSEA is too permissive",
    C:"正常，小 n 時 DE 表短 ORA 算不出東西；看 GSEA 的 leading edge 合不合理", C_en:"Normal — at small n the DE list is short so ORA has little to work with; read GSEA's leading edge",
    D:"把 ORA 的閾值放寬到 padj < 0.2", D_en:"Loosen ORA to padj < 0.2",
    ans:"C",
    exp:"ORA 先切閾值，清單短就湊不出顯著；GSEA 用整份排序，小 n 更靈敏。決定要不要寫進結論，看 leading edge。",
    exp_en:"ORA cuts a threshold first, so a short list cannot build a significant overlap; GSEA uses the whole ranking and is more sensitive at small n. The leading edge decides what goes into the conclusion." },
  { type:"single",
    stem:"整合之前先跑一版「不整合」的 UMAP 與分群，主要目的是？",
    stem_en:"Running an unintegrated UMAP and clustering before integration — what is it for?",
    A:"暖機，讓後面跑比較快", A_en:"To warm up so later steps run faster",
    B:"留下基線：看清楚原本的批次結構有多強，整合後才知道改了什麼、改掉多少", B_en:"To keep a baseline: see how strong the batch structure really is, so you can tell what integration changed and by how much",
    C:"沒有必要，整合後直接看就好", C_en:"It is unnecessary; just look after integration",
    D:"為了比較兩種 UMAP 參數", D_en:"To compare two sets of UMAP parameters",
    ans:"B",
    exp:"沒有基線就無法判斷整合是「修好了」還是「修過頭」。本課的原則更進一步：惡性細胞的分析一律回到未整合空間、按病人看。",
    exp_en:"Without a baseline you cannot tell whether integration fixed things or overcorrected. This course goes further: malignant-cell analysis returns to the unintegrated space, patient by patient." },
  { type:"single",
    stem:"padj = 0.05 的正確讀法是？",
    stem_en:"What does padj = 0.05 actually mean?",
    A:"這一個基因有 5% 的機率是假的", A_en:"This one gene has a 5% chance of being false",
    B:"在我宣告顯著的這一批基因裡，大約 5% 是假的", B_en:"Among the genes I am calling significant, about 5% are false",
    C:"這個基因的效應大小是 5%", C_en:"The effect size of this gene is 5%",
    D:"有 95% 的把握這個基因會重現", D_en:"There is 95% confidence the gene will replicate",
    ans:"B",
    exp:"BH 控制的是整批的錯誤發現率，不是單一基因的機率。校正的範圍就是「這一次跑的所有檢定」——每種細胞型別各自校正，不要把所有型別的 p 值倒在一起。",
    exp_en:"BH controls the false discovery rate over the whole set, not the probability for one gene. Correct within the set of tests actually run — per cell type, not pooled across types." },
  { type:"single",
    stem:"Bonferroni 與 BH 最主要的差別是？",
    stem_en:"What is the main difference between Bonferroni and BH?",
    A:"Bonferroni 比較新", A_en:"Bonferroni is newer",
    B:"Bonferroni 控制「一個假陽性都不要有」，非常保守；BH 控制整批的錯誤比例，找得回較多真訊號", B_en:"Bonferroni controls against any false positive at all and is very conservative; BH controls the proportion of errors in the set and recovers more true signal",
    C:"BH 不需要校正次數", C_en:"BH does not need the number of tests",
    D:"兩者結果永遠一樣", D_en:"They always give the same result",
    ans:"B",
    exp:"兩萬個檢定下 Bonferroni 的門檻壓到極低，真訊號多半被犧牲。單細胞的 DE 與富集慣例上報 BH（padj / p.adjust）。",
    exp_en:"Across twenty thousand tests Bonferroni pushes the threshold extremely low and sacrifices most true signal. Single-cell DE and enrichment conventionally report BH (padj / p.adjust)." },
  { type:"single",
    stem:"軌跡分析的起點怎麼選最站得住腳？",
    stem_en:"How should the root of a trajectory be chosen?",
    A:"選 UMAP 上最角落的那一群", A_en:"Pick the cluster in the far corner of the UMAP",
    B:"用已知的階層或 marker（例如幹細胞／前驅 marker）指定，並把理由寫下來", B_en:"Anchor it on a known hierarchy or markers (for example stem or progenitor markers), and record the reason",
    C:"讓演算法自己決定就好，不用管", C_en:"Let the algorithm decide; no need to intervene",
    D:"選細胞數最多的那一群", D_en:"Pick the cluster with the most cells",
    ans:"B",
    exp:"起點決定了整條軌跡的方向，換一個起點結論可能反過來。看圖挑角落是最容易被審稿人問倒的做法。",
    exp_en:"The root sets the direction of the whole trajectory; a different root can reverse the conclusion. Picking a corner by eye is what reviewers question first." },
  { type:"single",
    stem:"畫出一條漂亮的軌跡之後，最該先排除的替代解釋是？",
    stem_en:"After a clean trajectory appears, which alternative explanation should be excluded first?",
    A:"這條軌跡其實只是細胞週期", A_en:"The trajectory is really just the cell cycle",
    B:"這條軌跡是 UMAP 參數造成的", B_en:"The trajectory came from UMAP parameters",
    C:"這條軌跡是顏色造成的錯覺", C_en:"The trajectory is a colour illusion",
    D:"這條軌跡是細胞數太少造成的", D_en:"The trajectory is due to too few cells",
    ans:"A",
    exp:"增殖細胞在表現空間裡本來就連成一條線，很容易被當成分化軌跡。把 Phase 疊上去看，或先 regress 掉週期再跑一次。",
    exp_en:"Cycling cells naturally form a continuum in expression space and are easily mistaken for differentiation. Overlay Phase, or regress the cycle out and rerun." },
  { type:"single",
    stem:"路徑活性（PROGENy）或 regulon 活性（SCENIC）比起單純的差異表達，多告訴你什麼？",
    stem_en:"What do pathway activity (PROGENy) or regulon activity (SCENIC) add beyond plain differential expression?",
    A:"更小的 p 值", A_en:"Smaller p-values",
    B:"把一串基因收斂成「哪一條路徑／哪個轉錄因子被開起來」的解釋層次", B_en:"They condense a gene list into which pathway or transcription factor is switched on",
    C:"可以取代 DE，不必再做", C_en:"They replace DE, which then becomes unnecessary",
    D:"可以直接證明因果", D_en:"They prove causality directly",
    ans:"B",
    exp:"DE 給你基因，活性給你「這些基因是被誰開的」。兩者互補，都還是相關性層級的推論，不是因果。",
    exp_en:"DE gives genes; activity suggests what switched them on. They complement each other and both remain correlational, not causal." },
  { type:"single",
    stem:"用單細胞資料建 signature 去反卷積 bulk 隊列，最該先檢查的前提是？",
    stem_en:"Before deconvolving a bulk cohort with a single-cell signature, what must be checked?",
    A:"bulk 樣本數要超過 1,000", A_en:"The bulk cohort must exceed 1,000 samples",
    B:"signature 裡的細胞型別在那個 bulk 組織裡真的存在，且估出的比例合理", B_en:"The cell types in the signature really exist in that bulk tissue, and the estimated proportions are plausible",
    C:"單細胞與 bulk 要來自同一批病人", C_en:"Single-cell and bulk must come from the same patients",
    D:"兩邊的定序深度要一樣", D_en:"Sequencing depth must match on both sides",
    ans:"B",
    exp:"參考裡沒有的型別，比例會被硬塞給別的型別。先看加總與相對大小合不合理，再談跟臨床變項的關聯。",
    exp_en:"Types missing from the reference get their signal forced onto other types. Check that the proportions sum and rank sensibly before relating them to clinical variables." },
  { type:"single",
    stem:"反卷積算出某個族群比例後做存活分析，最常見的問題是？",
    stem_en:"Running survival analysis on a deconvolved cell fraction — what is the most common pitfall?",
    A:"沒有放期別、年齡這些共變量，也沒說明切點怎麼定", A_en:"Omitting covariates such as stage and age, and not stating how the cut-point was chosen",
    B:"KM 曲線畫得不好看", B_en:"The KM curve looks unattractive",
    C:"樣本數太多", C_en:"Too many samples",
    D:"應該改用 t 檢定", D_en:"A t-test should be used instead",
    ans:"A",
    exp:"高低分組的切點如果試過很多個只報最顯著的那一個，p 值就沒有意義了。要嘛事先鎖定切點，要嘛把試過的全部報出來，並用 Cox 放進共變量。",
    exp_en:"If many cut-points are tried and only the most significant is reported, the p-value is meaningless. Fix the cut-point in advance or report them all, and put covariates into a Cox model." },
  { type:"single",
    stem:"CellChat 的結果再用 LIANA 跑一次，用意是？",
    stem_en:"Why rerun the CellChat result through LIANA?",
    A:"讓 p 值變小", A_en:"To lower the p-values",
    B:"換一套方法與資料庫做交叉驗證：兩邊都出現的訊號比較可信", B_en:"Cross-validation with a different method and database: signals appearing in both are more trustworthy",
    C:"LIANA 比較快", C_en:"LIANA is faster",
    D:"CellChat 的結果一定是錯的", D_en:"CellChat results are always wrong",
    ans:"B",
    exp:"通訊推論高度依賴 L-R 資料庫與評分方式。換一套工具重跑，是把「工具造成的結果」與「資料裡的訊號」分開最省力的辦法。",
    exp_en:"Communication inference depends heavily on the L-R database and scoring. Rerunning with another tool is the cheapest way to separate tool artefacts from signal in the data." },
  { type:"single",
    stem:"不能做 pseudobulk（例如只有 2 位病人）時，cell-level DE 的三道防線是什麼？",
    stem_en:"When pseudobulk is impossible (say only two patients), what are the three safeguards for cell-level DE?",
    A:"提高 log2FC 門檻、只看前 50 名、改用 t 檢定", A_en:"Raise the log2FC cut-off, keep the top 50, switch to a t-test",
    B:"把病人放進模型當共變量、檢查結論在每位病人身上是否一致、做標籤置換看隨機能得到多少", B_en:"Put patient into the model as a covariate, check consistency within each patient, and permute labels to see what randomness alone yields",
    C:"改用 UMAP 分群、換 resolution、重跑整合", C_en:"Recluster on UMAP, change resolution, redo integration",
    D:"只報 padj < 0.001 的基因", D_en:"Report only genes with padj < 0.001",
    ans:"B",
    exp:"cell-level DE 把同一位病人的細胞當成獨立樣本，p 值會嚴重膨脹。三道防線不能讓它變正確，只能讓你知道結論有多脆弱，並在交付時標明限制。",
    exp_en:"Cell-level DE treats cells from one patient as independent samples, inflating p-values badly. The safeguards do not make it correct — they show how fragile the conclusion is, and the limitation must be stated on delivery." },
  { type:"single",
    stem:"要在 Seurat CCA 與 Harmony 之間選一個，最合理的依據是？",
    stem_en:"Choosing between Seurat CCA and Harmony — what is the sound basis?",
    A:"哪一個的 UMAP 看起來比較乾淨", A_en:"Whichever UMAP looks cleaner",
    B:"正負對照一起看：正常細胞誰混得好、惡性細胞誰保得住", B_en:"Read both controls together: which mixes normal cells better, and which preserves malignant patient structure",
    C:"哪一個跑得比較快", C_en:"Whichever runs faster",
    D:"論文引用數比較高的那個", D_en:"Whichever is cited more",
    ans:"B",
    exp:"「看起來乾淨」常常正是過度修正。用免疫／寡樹突當正對照、惡性細胞當負對照，配合 LISI 一起比，才有依據。",
    exp_en:"Looking clean is often exactly what overcorrection looks like. Use immune and oligodendrocyte cells as positive controls and malignant cells as the negative control, alongside LISI." },
  { type:"single",
    stem:"本課的原則是「惡性細胞的分析回到未整合空間」。為什麼？",
    stem_en:"This course analyses malignant cells in the unintegrated space. Why?",
    A:"未整合空間跑得比較快", A_en:"It runs faster",
    B:"惡性細胞的病人間差異帶著各自的 CNV，是生物訊號；整合演算法分不出來，會一律當批次抹平", B_en:"Between-patient differences in malignant cells carry each patient's CNV — real biology that integration cannot distinguish from batch and flattens away",
    C:"整合後的資料不能做 DE", C_en:"Integrated data cannot be used for DE",
    D:"未整合空間的 UMAP 比較好看", D_en:"The unintegrated UMAP looks better",
    ans:"B",
    exp:"整合空間拿來註釋正常細胞、對齊免疫細胞很好用；惡性細胞則按病人分開看。這是「兩難」的實務解法。",
    exp_en:"The integrated space is good for annotating normal cells and aligning immune cells; malignant cells are examined patient by patient. That is the practical resolution of the dilemma." },
  { type:"single",
    stem:"inferCNV 的觀察組（observation）與參考組（reference）該怎麼分？",
    stem_en:"How should inferCNV observation and reference groups be split?",
    A:"參考組隨機抽一半細胞", A_en:"Randomly take half the cells as reference",
    B:"參考組放確定正常的細胞（免疫、寡樹突），觀察組按病人分開", B_en:"Put confidently normal cells (immune, oligodendrocyte) in the reference, and split observations by patient",
    C:"參考組放惡性細胞", C_en:"Put malignant cells in the reference",
    D:"不需要參考組", D_en:"No reference group is needed",
    ans:"B",
    exp:"參考組定義了「正常長什麼樣」，選錯就整份結果偏掉。觀察組按病人分開，是因為 CNV 本來就是各病人自己的。",
    exp_en:"The reference defines what normal looks like; choosing it wrongly skews everything. Observations are split by patient because CNV is patient-specific by nature." },
  { type:"single",
    stem:"CNV 分數與 CNV 相關性的「四象限圖」怎麼讀？",
    stem_en:"How do you read the four-quadrant plot of CNV score versus CNV correlation?",
    A:"只要分數高就是惡性", A_en:"High score alone means malignant",
    B:"兩個指標都高才是可信的惡性；只有一個高的細胞要標成不確定，不要硬分", B_en:"Both high is a confident malignant call; cells high on only one axis are uncertain and should not be forced",
    C:"相關性高就是正常細胞", C_en:"High correlation means normal",
    D:"四個象限沒有差別", D_en:"The four quadrants are equivalent",
    ans:"B",
    exp:"分數量的是「偏離參考多少」，相關性量的是「偏離的模式跟惡性群一不一致」。兩個一起看，才能把雜訊與真的 CNV 分開。",
    exp_en:"The score measures how far a cell departs from the reference; the correlation measures whether that departure matches the malignant pattern. Together they separate noise from real CNV." },
  { type:"single",
    stem:"惡性判定的「三角驗證」指的是哪三種證據？",
    stem_en:"What three lines of evidence make up the triangulation for malignancy?",
    A:"三種不同的分群演算法", A_en:"Three clustering algorithms",
    B:"CNV 證據、跨病人專屬性（惡性細胞按病人分群）、與已知譜系／狀態標記的一致性", B_en:"CNV evidence, patient-specificity (malignant cells cluster by patient), and consistency with known lineage or state markers",
    C:"三位不同的人各標一次", C_en:"Three people annotating independently",
    D:"三個不同的參考資料庫", D_en:"Three different reference databases",
    ans:"B",
    exp:"單一證據都可能被別的原因解釋。三個方向指向同一個結論，那個標籤才站得住——這也是為什麼腳本要把三件事都輸出。",
    exp_en:"Any single line of evidence has alternative explanations. When three point the same way the label holds — which is why the script outputs all three." },
  { type:"single",
    stem:"propeller（組成分析）比「直接比較兩組的細胞比例」多做了什麼？",
    stem_en:"What does propeller add over simply comparing cell proportions between groups?",
    A:"沒有差別，只是換個套件", A_en:"Nothing; it is just another package",
    B:"把比例做變數穩定轉換、以樣本為單位建模，並處理比例資料「一個上升別的必定下降」的相依性", B_en:"It variance-stabilises the proportions, models at the sample level, and handles the dependence inherent in proportions — one rising forces others down",
    C:"自動幫你分群", C_en:"It clusters for you",
    D:"可以不用重複樣本", D_en:"It removes the need for replicates",
    ans:"B",
    exp:"比例是總和為 1 的資料，直接做 t 檢定會低估變異也忽略相依。而且統計單位一樣是樣本／病人，不是細胞。",
    exp_en:"Proportions sum to one, so a plain t-test underestimates variance and ignores the dependence. And the unit is still the sample or patient, not the cell." },
  { type:"single",
    stem:"DESeq2 的 shrunken log2FC（例如 ashr）跟原始 log2FC 差在哪？",
    stem_en:"How does a shrunken log2FC (for example via ashr) differ from the raw one?",
    A:"shrunken 一定比較大", A_en:"Shrunken values are always larger",
    B:"低表現、變異大的基因其誇張的 log2FC 會被收斂，排序更穩定；畫圖與排名建議用 shrunken", B_en:"Exaggerated fold changes from low-expressed, noisy genes are pulled in, giving a more stable ranking; use shrunken values for plots and ranking",
    C:"shrunken 會改變 p 值", C_en:"Shrinkage changes the p-values",
    D:"兩者完全一樣", D_en:"They are identical",
    ans:"B",
    exp:"少數幾個 count 就能算出很大的 log2FC，那是雜訊不是效應。收縮之後的排序拿去做 GSEA 也比較不會被極端值帶偏。",
    exp_en:"A handful of counts can produce a huge fold change — noise, not effect. A shrunken ranking also keeps GSEA from being dragged by extremes." },
  { type:"single",
    stem:"火山圖左右不對稱，是不是代表分析做錯了？",
    stem_en:"An asymmetric volcano plot — does that mean the analysis is wrong?",
    A:"是，火山圖應該左右對稱", A_en:"Yes, volcano plots should be symmetric",
    B:"不是；生物上本來就可能一邊的變化比較多，對稱與否不是品質指標", B_en:"No; biology can genuinely change more in one direction, and symmetry is not a quality metric",
    C:"是，代表 design 寫反了", C_en:"Yes, it means the design formula is reversed",
    D:"是，代表要重新正規化", D_en:"Yes, it means renormalisation is needed",
    ans:"B",
    exp:"該檢查的是別的東西：log2FC 是不是全部擠在 0 附近（可能是 pseudoreplication 或效應太小）、以及方向跟你的對比定義一不一致。",
    exp_en:"Check other things instead: whether all fold changes crowd around zero (possible pseudoreplication or a tiny effect), and whether the direction matches how the contrast was defined." },
  { type:"single",
    stem:"GSEA 的 NES 是什麼？",
    stem_en:"What is the NES in GSEA?",
    A:"顯著基因的數量", A_en:"The number of significant genes",
    B:"標準化後的富集分數：正負表示這個基因集偏向排序的哪一端，絕對值表示偏得多明顯", B_en:"The normalised enrichment score: its sign shows which end of the ranking the set leans towards, its magnitude how strongly",
    C:"基因集的大小", C_en:"The size of the gene set",
    D:"p 值的倒數", D_en:"The reciprocal of the p-value",
    ans:"B",
    exp:"標準化是為了讓不同大小的基因集可以互相比較。報結果時 NES 與 padj 要一起給，並看 leading edge 是哪些基因在撐。",
    exp_en:"Normalisation makes sets of different sizes comparable. Report NES with padj, and check which genes in the leading edge carry the signal." },
  { type:"single",
    stem:"同一份排序清單，Hallmark、GO、KEGG 三個資料庫的結果不一樣。最合理的處理？",
    stem_en:"Hallmark, GO and KEGG give different answers for the same ranked list. What is the sensible response?",
    A:"挑最顯著的那個資料庫報", A_en:"Report whichever database gives the most significant result",
    B:"這很正常——三者的粒度與整理方式不同；報告時說明用了哪一個、為什麼，並看跨資料庫一致的主題", B_en:"That is normal — they differ in granularity and curation; state which you used and why, and look for themes consistent across them",
    C:"代表分析做錯了要重跑", C_en:"It means the analysis is wrong and must be redone",
    D:"三個結果取平均", D_en:"Average the three results",
    ans:"B",
    exp:"Hallmark 粒度粗、訊號乾淨，適合起手；GO 細但冗餘高；KEGG 偏代謝與訊號路徑。挑資料庫本身就是一個要交代的決定。",
    exp_en:"Hallmark is coarse and clean, good to start with; GO is fine-grained but redundant; KEGG leans metabolic and signalling. The choice of database is itself a decision to report." },
  { type:"single",
    stem:"CellChat 的 filterCommunication(min.cells = 10) 會造成什麼後果？",
    stem_en:"What is the effect of CellChat's filterCommunication(min.cells = 10)?",
    A:"把訊號弱的邊畫淡一點", A_en:"It draws weak edges faintly",
    B:"細胞數不足的族群會整組退出網路——某條互動「不見了」可能是沒訊號，也可能是那一群根本沒進網路", B_en:"Groups below the threshold drop out of the network entirely — a missing interaction may mean no signal, or that the group never entered the network",
    C:"只影響顏色", C_en:"It only affects colours",
    D:"會自動補足細胞數", D_en:"It automatically tops up the cell number",
    ans:"B",
    exp:"所以每次跑完要輸出「哪幾群撐過門檻」的表。少了這張表，讀圖的人分不出「沒有訊號」與「沒進網路」。",
    exp_en:"So always output a table of which groups survived the threshold. Without it, readers cannot tell absence of signal from absence from the network." },
  { type:"single",
    stem:"tradeSeq 在軌跡分析裡負責什麼？",
    stem_en:"What does tradeSeq do in trajectory analysis?",
    A:"決定軌跡的起點", A_en:"It chooses the root of the trajectory",
    B:"沿著擬時間為每個基因配適平滑曲線，找出表現隨軌跡顯著變化、或在分支之間不同的基因", B_en:"It fits smooth curves along pseudotime per gene, finding genes that change along the trajectory or differ between branches",
    C:"把細胞投影到 UMAP", C_en:"It projects cells onto the UMAP",
    D:"移除批次效應", D_en:"It removes batch effects",
    ans:"B",
    exp:"Slingshot（或 Monocle）給軌跡與擬時間，tradeSeq 回答「沿路哪些基因在動」。兩者分工不同，通常一起用。",
    exp_en:"Slingshot (or Monocle) provides the trajectory and pseudotime; tradeSeq answers which genes move along it. They divide the work and are usually used together." },
  { type:"single",
    stem:"SCENIC 的 regulon 活性與「這個轉錄因子的表現量」差在哪？",
    stem_en:"How does SCENIC regulon activity differ from the transcription factor's own expression?",
    A:"完全一樣，只是換算單位", A_en:"They are the same, just rescaled",
    B:"regulon 看的是它的下游目標基因整體有沒有被開起來——TF 本身測不到時仍可能有活性", B_en:"A regulon reads whether its downstream targets are collectively switched on — activity can be present even when the TF itself is not detected",
    C:"regulon 只看蛋白質層級", C_en:"Regulons work at the protein level",
    D:"regulon 不需要資料就能算", D_en:"Regulons need no data" ,
    ans:"B",
    exp:"轉錄因子本身往往表現低、又常掉進 dropout。看下游目標的集體行為，訊噪比好得多——但它仍是推論，不是實測的結合事件。",
    exp_en:"Transcription factors are often lowly expressed and lost to dropout. Reading the collective behaviour of their targets is far less noisy — though it remains an inference, not a measured binding event." },
  { type:"single",
    stem:"反卷積得到的細胞比例，和單細胞資料裡直接數出來的比例對不起來。最該先想到什麼？",
    stem_en:"Deconvolved proportions do not match the ones counted directly in the single-cell data. What comes to mind first?",
    A:"反卷積一定算錯了", A_en:"The deconvolution must be wrong",
    B:"兩者測的本來就不是同一件事：單細胞的比例受解離與 QC 影響，bulk 反映的是組織裡的實際組成", B_en:"They measure different things: single-cell proportions are shaped by dissociation and QC, while bulk reflects the actual tissue composition",
    C:"bulk 資料品質不好", C_en:"The bulk data is poor quality",
    D:"要把單細胞的比例改成跟反卷積一樣", D_en:"Adjust the single-cell proportions to match",
    ans:"B",
    exp:"解離會流失特定細胞型別、QC 又會再篩一次。兩邊的比例不必一致，但方向性的差異（哪一組比較高）如果也相反，那才要回頭檢查。",
    exp_en:"Dissociation loses certain types and QC filters again. The two need not agree in absolute terms; it is when the direction of the difference disagrees that you should look again." },
],

}};

const labels_en = {
  "Q1：觀念篇": "Q1: Concepts",
  "Q2：實作篇 I": "Q2: Hands-on I",
  "Q3：實作篇 II": "Q3: Hands-on II",
};
