/* Q 系列（快速上手篇）自測題庫 v5 — 與 A/B 系列題庫同結構。
 * Q1 7 題、Q2 9 題、Q3 11 題：前 3 題與影片「自測」相同，後 4 題取自踩雷區、v4 新增頁與腳本練習。
 */
const subjects = {
"Q 系列 · 快速上手篇": {

"Q1：觀念篇": [
  { type:"single",
    stem:"bulk RNA-seq 顯示腫瘤 A 的 CD8A 比腫瘤 B 高三倍。最保守的解讀？",
    stem_en:"Bulk shows CD8A three-fold higher in tumour A than B. The most conservative reading?",
    A:"A 的 T 細胞更有攻擊性", A_en:"A's T cells are more cytotoxic",
    B:"A 的 CD8 T 細胞比例可能較高，或每顆表現較高——bulk 分不開", B_en:"A may have more CD8 T cells, or each expresses more — bulk cannot tell",
    C:"A 對免疫治療反應較好", C_en:"A will respond better to immunotherapy",
    D:"B 的樣本純度較低", D_en:"B has lower purity",
    ans:"B",
    exp:"組成改變與內在改變在 bulk 裡長得一樣；A、C 是過度詮釋，D 是無根據的猜測。",
    exp_en:"Composition and intrinsic change look identical in bulk; A and C over-interpret, D is a guess." },
  { type:"single",
    stem:"四位病人的 GBM 資料，UMAP 上惡性細胞分成四座島、巨噬細胞混成一群。這代表？",
    stem_en:"Four GBM patients: malignant cells form four islands, macrophages one blended cluster. This means?",
    A:"嚴重批次效應，要整合", A_en:"Severe batch effect; integrate",
    B:"惡性細胞有四種亞型", B_en:"Four malignant subtypes",
    C:"正常現象：惡性細胞帶病人特異的 CNV，正常細胞沒有", C_en:"Expected: malignant cells carry patient-specific CNV, normal cells do not",
    D:"巨噬細胞的資料品質較差", D_en:"Macrophage data quality is poorer",
    ans:"C",
    exp:"巨噬細胞混合良好證明技術批次小；惡性分島來自基因體差異，硬整合會抹掉真實生物學。",
    exp_en:"Well-blended macrophages prove technical batch is small; malignant islands come from genomic differences." },
  { type:"single",
    stem:"要證明某群細胞是惡性的，最有力的證據是？",
    stem_en:"The strongest evidence that a cluster is malignant?",
    A:"高表現 EGFR、SOX2", A_en:"High EGFR and SOX2",
    B:"整段染色體（如 chr7 增加、chr10 缺失）的表現一起偏移", B_en:"Whole chromosome arms shifting together (chr7 gain, chr10 loss)",
    C:"在 UMAP 上離免疫細胞很遠", C_en:"Far from immune cells on the UMAP",
    D:"細胞比較大、nCount 比較高", D_en:"Larger cells with higher nCount",
    ans:"B",
    exp:"marker 只說譜系、UMAP 距離無證據力、nCount 反映 RNA 量；CNV 是基因體層級證據。",
    exp_en:"Markers give lineage, UMAP distance is not evidence, nCount reflects RNA content; CNV is genome-level evidence." },
  { type:"single",
    stem:"一群 FOS、JUN、HSPA1A 高表現的細胞，同時出現在惡性、巨噬、寡樹突細胞裡各一撮。最可能是？",
    stem_en:"A FOS/JUN/HSPA1A-high group appears as a slice within malignant, macrophage and oligodendrocyte cells. Most likely?",
    A:"腫瘤誘導的共同壓力反應（真發現）", A_en:"A tumour-induced shared stress programme (real)",
    B:"解離時的立即早期反應（技術假象）", B_en:"Dissociation-induced immediate-early response (artefact)",
    C:"doublet", C_en:"Doublets",
    D:"週期 G2/M 期", D_en:"G2/M phase",
    ans:"B",
    exp:"跨型別出現、立即早期基因 + 熱休克蛋白，是解離壓力的典型長相；腫瘤組織解離時間長，訊號特別強。",
    exp_en:"Cross-type appearance of IEGs plus heat-shock genes is the classic dissociation signature; tumours dissociate slowly so it is strong." },
  { type:"single",
    stem:"10x 矩陣裡的數字是什麼？",
    stem_en:"What are the numbers in a 10x matrix?",
    A:"read 數", A_en:"Read counts",
    B:"UMI 分子數（PCR 重複已去除）", B_en:"UMI molecule counts (PCR duplicates removed)",
    C:"TPM", C_en:"TPM",
    D:"log 表現量", D_en:"log expression",
    ans:"B",
    exp:"UMI 讓同一分子的 PCR 複製只算一次；這是單細胞計數資料與 bulk read count 的根本差別。",
    exp_en:"UMIs count each molecule once regardless of PCR copies — the fundamental difference from bulk reads." },
  { type:"single",
    stem:"預算固定，你只能二選一：多收 1 位病人，或把每個樣本從 5,000 顆細胞增加到 15,000 顆。研究問題是「核心 vs 邊緣的惡性細胞差異」。該選？",
    stem_en:"Fixed budget, one choice: one more patient, or 5,000 → 15,000 cells per sample. The question is 'core vs periphery malignant cells'. Which?",
    A:"多收病人：統計功效來自病人數，細胞數過了膝點就沒有幫助", A_en:"More patients: power comes from patients; cells past the knee do not help",
    B:"多收細胞：細胞越多 p 值越小", B_en:"More cells: more cells, smaller p",
    C:"多收細胞：才能看到稀有群", C_en:"More cells: needed to see rare populations",
    D:"兩者一樣", D_en:"No difference",
    ans:"A",
    exp:"n 是病人；惡性細胞不是稀有群，5,000 顆已足夠。C 只在研究問題是稀有群時成立。",
    exp_en:"n is patients; malignant cells are not rare, 5,000 is plenty. C holds only when the question is about a rare population." },
  { type:"single",
    stem:"FeaturePlot 上 MBP 在寡樹突細胞很亮，但每一顆細胞都有一點顏色。最可能的原因？",
    stem_en:"On a FeaturePlot MBP is bright in oligodendrocytes but every cell shows a little colour. Most likely cause?",
    A:"所有細胞都有寡樹突分化潛能", A_en:"Every cell has oligodendrocyte potential",
    B:"環境 RNA：裂解細胞的 mRNA 漂進了每顆液滴", B_en:"Ambient RNA: mRNA from lysed cells drifted into every droplet",
    C:"normalization 做錯", C_en:"Normalization error",
    D:"doublet", D_en:"Doublets",
    ans:"B",
    exp:"門牌基因「到處都有一點」是環境 RNA 的典型樣子；SoupX 可估計並扣除。doublet 是少數細胞同時亮兩種 marker，不是全部細胞。",
    exp_en:"A gate gene showing a little everywhere is the signature of ambient RNA; SoupX estimates and removes it. Doublets are a few cells lighting two markers, not all cells." },
],

"Q2：實作篇 I": [
  { type:"single",
    stem:"GBM 資料 percent.mt 中位數 7%、median + 3×MAD = 13%。閾值該怎麼定？",
    stem_en:"GBM: median percent.mt 7%, median + 3×MAD = 13%. Where does the cutoff go?",
    A:"照慣例 5%", A_en:"The conventional 5%",
    B:"13%，並把數字與理由寫進方法段", B_en:"13%, with number and reason in the methods",
    C:"不過濾 percent.mt", C_en:"Skip the filter",
    D:"取兩者平均 9%", D_en:"Average them: 9%",
    ans:"B",
    exp:"閾值是資料的性質。5% 砍掉大半活細胞；不過濾留下垂死細胞的第二個峰；9% 沒有理由。",
    exp_en:"A threshold is a property of the data. 5% removes most live cells; no filter keeps the dying mode; 9% has no rationale." },
  { type:"single",
    stem:"某群同時高表現 SOX2 與 C1QB，scDblFinder 標記其中 65% 為 doublet。該怎麼處理？",
    stem_en:"A cluster expresses SOX2 and C1QB; scDblFinder flags 65%. What now?",
    A:"有趣的新亞群，寫進結果", A_en:"Exciting new subset — report it",
    B:"整群移除並記錄理由", B_en:"Remove the whole cluster and record why",
    C:"只移除被標記的 65%", C_en:"Remove only the flagged 65%",
    D:"提高 resolution 把它再切開", D_en:"Raise resolution to split it",
    ans:"B",
    exp:"過半被標記且卡在惡性與髓系之間，整群是 doublet 產物；剩下的是工具沒抓到的。",
    exp_en:"Mostly flagged and sitting between malignant and myeloid: the whole cluster is a doublet product." },
  { type:"single",
    stem:"SingleR 把 0 號群標成 Astrocyte，marker 是 SOX2 / PTPRZ1 / EGFR。最誠實的標籤？",
    stem_en:"SingleR labels cluster 0 Astrocyte; markers SOX2 / PTPRZ1 / EGFR. The honest label?",
    A:"Astrocyte", A_en:"Astrocyte",
    B:"Malignant", B_en:"Malignant",
    C:"Glial（惡性待 CNV 判定）", C_en:"Glial (malignancy pending CNV)",
    D:"Neural progenitor", D_en:"Neural progenitor",
    ans:"C",
    exp:"參考集裡沒有 GBM 惡性細胞；marker 只說譜系。惡性要 CNV 證據。",
    exp_en:"No GBM malignant cells in any reference; markers only give lineage. Malignancy needs CNV." },
  { type:"single",
    stem:"nFeature_RNA 與 nCount_RNA 的 MAD 閾值為什麼要在 log10 尺度算？",
    stem_en:"Why compute MAD cutoffs for nFeature / nCount on the log10 scale?",
    A:"因為 Seurat 預設這樣做", A_en:"Because Seurat does it by default",
    B:"它們是對數常態分布，原始尺度的 MAD 會被長尾拉歪", B_en:"They are log-normal; MAD on the raw scale is distorted by the long tail",
    C:"為了讓數字比較小", C_en:"To make the numbers smaller",
    D:"percent.mt 也要在 log 尺度算", D_en:"percent.mt should also be on log scale",
    ans:"B",
    exp:"對數常態資料在 log 尺度才對稱，MAD 才有意義；percent.mt 是比例，直接算。",
    exp_en:"Log-normal data is symmetric only on the log scale; percent.mt is a proportion and is computed directly." },
  { type:"single",
    stem:"一群 MKI67、TOP2A 高的細胞自成一島。最合理的解讀？",
    stem_en:"An MKI67/TOP2A-high island. The most reasonable reading?",
    A:"幹細胞樣亞群", A_en:"A stem-like subpopulation",
    B:"增殖狀態，可能混了多種型別；先看 Phase 欄位", B_en:"A cycling state, possibly mixing several types; check the Phase column first",
    C:"doublet", C_en:"Doublets",
    D:"低品質細胞", D_en:"Low-quality cells",
    ans:"B",
    exp:"週期是狀態不是型別；先算週期分數才看得出來，再決定要不要 regress。",
    exp_en:"Cell cycle is a state, not a type; score it first, then decide whether to regress." },
  { type:"single",
    stem:"FindAllMarkers 給某群一個「marker」：avg_log2FC = 2.1、pct.1 = 0.28、pct.2 = 0.03、p_val_adj < 1e-100。該怎麼看？",
    stem_en:"FindAllMarkers reports a 'marker' with avg_log2FC = 2.1, pct.1 = 0.28, pct.2 = 0.03, p_val_adj < 1e-100. How to read it?",
    A:"p 值極小，是很強的 marker", A_en:"Tiny p, a very strong marker",
    B:"pct.1 只有 0.28：它描述的是群的一部分，裡面可能藏著亞群或 doublet", B_en:"pct.1 is only 0.28: it describes part of the cluster — a hidden subset or doublets",
    C:"pct.2 太低，是雜訊", C_en:"pct.2 too low, noise",
    D:"FC 不夠大", D_en:"FC not large enough",
    ans:"B",
    exp:"好的 marker 要 pct.1 > 0.5；p 值在幾千顆細胞下幾乎都極小，只當篩子。",
    exp_en:"A good marker needs pct.1 > 0.5; with thousands of cells p is always tiny and serves only as a sieve." },
  { type:"single",
    stem:"你用了 SCTransform。接下來要做 pseudobulk DE 與 inferCNV，該拿哪一層的值？",
    stem_en:"You used SCTransform. For pseudobulk DE and inferCNV, which layer do you use?",
    A:"SCT assay 的 data 層", A_en:"The SCT assay's data layer",
    B:"SCT assay 的 scale.data 層", B_en:"The SCT assay's scale.data layer",
    C:"RNA assay 的 counts 層", C_en:"The RNA assay's counts layer",
    D:"哪一層都可以", D_en:"Any layer",
    ans:"C",
    exp:"DE、CNV、pseudobulk 都需要原始整數 counts；SCT 的值只用於降維與視覺化。",
    exp_en:"DE, CNV and pseudobulk need raw integer counts; SCT values are for dimensionality reduction and visualisation." },
  { type:"single",
    stem:"你想把免疫細胞細分成小膠質、血液來源巨噬細胞、CD4/CD8 T。最正確的做法？",
    stem_en:"You want to split immune cells into microglia, blood-derived macrophages and CD4/CD8 T. The correct approach?",
    A:"在全體的 UMAP 上把免疫大陸用更高的 resolution 再切", A_en:"Re-cluster the immune continent at higher resolution on the global UMAP",
    B:"subset 出免疫細胞，重算 HVG、PCA、分群、UMAP，再用免疫 marker 面板註釋", B_en:"Subset immune cells, recompute HVGs, PCA, clusters and UMAP, then annotate with an immune panel",
    C:"直接用 SingleR 的 label.fine", C_en:"Just use SingleR's label.fine",
    D:"用 FeaturePlot 手動圈", D_en:"Circle them manually on a FeaturePlot",
    ans:"B",
    exp:"全體的 HVG 與前幾個 PC 被「惡性 vs 免疫」佔滿，亞群訊號排不進去；subset 後一定重算。SingleR 可當第二證人但不是答案。",
    exp_en:"Global HVGs and top PCs are dominated by malignant-vs-immune; subset signal is excluded. Always recompute after subsetting. SingleR is a second witness, not the answer." },
  { type:"single",
    stem:"一群細胞只有 MKI67、TOP2A 顯著，其他 marker 跟旁邊的巨噬細胞一樣，Phase 幾乎全是 S/G2M。該怎麼註釋？",
    stem_en:"A cluster is significant only for MKI67 and TOP2A, otherwise matches neighbouring macrophages, and is nearly all S/G2M. How to annotate?",
    A:"新型別：腫瘤幹細胞", A_en:"A new type: tumour stem cells",
    B:"Cycling macrophage：狀態，併回巨噬細胞並在第三層標註", B_en:"Cycling macrophage: a state, merged back into macrophages and noted at level 3",
    C:"移除，因為是 doublet", C_en:"Remove as doublets",
    D:"回歸週期後重新命名", D_en:"Regress the cycle and rename",
    ans:"B",
    exp:"增殖是狀態不是型別；命名用「形容詞 + 型別」，存在 celltype_l3。",
    exp_en:"Proliferation is a state, not a type; name it 'adjective + type' and store at celltype_l3." },
],

"Q3：實作篇 II": [
  { type:"single",
    stem:"跑 inferCNV 時，哪一組最適合當參考細胞？",
    stem_en:"Safest inferCNV reference?",
    A:"表現 GFAP 的星狀細胞群", A_en:"The GFAP-expressing astrocyte cluster",
    B:"免疫細胞與寡樹突細胞", B_en:"Immune cells and oligodendrocytes",
    C:"UMAP 上離惡性細胞最遠的群", C_en:"Whatever is farthest from malignant cells on the UMAP",
    D:"所有非惡性標籤的細胞", D_en:"All cells not labelled malignant",
    ans:"B",
    exp:"參考組必須確定沒有 CNV；星狀細胞可能是 AC 樣惡性細胞；UMAP 距離不是證據。",
    exp_en:"References must be CNV-free; astrocytes may be AC-like malignant cells; UMAP distance is not evidence." },
  { type:"single",
    stem:"Harmony 之後惡性細胞混成一團。這代表？",
    stem_en:"After Harmony, malignant cells are one blended cluster. This means?",
    A:"整合成功，直接做下游", A_en:"Integration worked; proceed",
    B:"整合把病人特異的 CNV 生物學修掉了；惡性分析回未整合空間", B_en:"Patient-specific CNV biology was erased; analyse malignant cells in the unintegrated space",
    C:"四位病人是同一亞型", C_en:"The four patients share a subtype",
    D:"要提高 theta 再整合一次", D_en:"Raise theta and integrate again",
    ans:"B",
    exp:"惡性按病人分島是基因體差異；整合空間只拿來註釋正常細胞。",
    exp_en:"Malignant patient islands are genomic; the integrated space is for annotating normal cells only." },
  { type:"single",
    stem:"核心 vs 邊緣的惡性細胞 DE，DESeq2 的 design？",
    stem_en:"Design for core vs periphery malignant DE?",
    A:"~ tissue", A_en:"~ tissue",
    B:"~ patient + tissue", B_en:"~ patient + tissue",
    C:"~ tissue + n_cells", C_en:"~ tissue + n_cells",
    D:"~ tissue * patient", D_en:"~ tissue * patient",
    ans:"B",
    exp:"配對設計先吸掉病人差異；細胞數已由 pseudobulk 處理；交互作用項在 n = 4 時無法估計。",
    exp_en:"Paired design absorbs patient first; cell number is handled by pseudobulk; an interaction cannot be estimated at n = 4." },
  { type:"single",
    stem:"pseudobulk 只取惡性細胞而不是所有細胞，是為了？",
    stem_en:"Why pseudobulk malignant cells only, not all cells?",
    A:"減少計算量", A_en:"To save compute",
    B:"否則比的是組成（邊緣的正常腦細胞較多），不是惡性細胞的變化", B_en:"Otherwise you compare composition (more normal brain at the periphery), not malignant-cell change",
    C:"DESeq2 只接受單一型別", C_en:"DESeq2 accepts one type only",
    D:"惡性細胞的 counts 比較大", D_en:"Malignant cells have larger counts",
    ans:"B",
    exp:"不同部位的型別組成不同；混合加總後的差異大半來自組成，MBP、PLP1 會衝到前面。",
    exp_en:"Composition differs by site; pooled differences are mostly composition — MBP and PLP1 rise to the top." },
  { type:"single",
    stem:"「邊緣的惡性細胞比例從 65% 降到 20%」，四位病人各一對樣本。該用什麼檢定？",
    stem_en:"'Malignant fraction drops from 65% to 20% at the periphery', four paired samples. Which test?",
    A:"對比例做配對 t-test", A_en:"Paired t-test on the proportions",
    B:"propeller（logit 轉換 + limma，樣本為單位、配對）", B_en:"propeller (logit + limma, sample-level, paired)",
    C:"對細胞做卡方檢定", C_en:"Chi-square on cells",
    D:"不用檢定，差異很明顯", D_en:"No test needed; the difference is obvious",
    ans:"B",
    exp:"比例是組成資料且單位是樣本；卡方把細胞當獨立觀察值（pseudoreplication）。",
    exp_en:"Proportions are compositional and the unit is the sample; chi-square treats cells as independent (pseudoreplication)." },
  { type:"single",
    stem:"Harmony 整合後，免疫細胞的 LISI 中位數約 3.6、惡性細胞約 1.2（四位病人）。這代表？",
    stem_en:"After Harmony, median LISI ≈ 3.6 for immune cells and ≈ 1.2 for malignant cells (four patients). This means?",
    A:"整合失敗，惡性細胞沒混好，要調高 theta", A_en:"Integration failed for malignant cells; raise theta",
    B:"正確：正常細胞跨病人混合、惡性細胞保留病人差異", B_en:"Correct: normal cells blend across patients, malignant cells keep patient differences",
    C:"免疫細胞被過度修正", C_en:"Immune cells are over-corrected",
    D:"LISI 不能用在 Harmony", D_en:"LISI does not apply to Harmony",
    ans:"B",
    exp:"免疫細胞 LISI 接近病人數 = 整合成功；惡性細胞接近 1 = 病人特異 CNV 被保住，正是我們要的。",
    exp_en:"Immune LISI near the patient count = integration worked; malignant near 1 = patient-specific CNV preserved, exactly as intended." },
  { type:"single",
    stem:"把 Smart-seq2 的 inferCNV 參數（cutoff = 1）直接用在 10x 資料上，最可能的結果？",
    stem_en:"Using the Smart-seq2 inferCNV cutoff (= 1) directly on 10x data most likely gives?",
    A:"熱圖幾乎空白：多數基因因平均表現低於 cutoff 被丟掉", A_en:"A nearly blank heatmap: most genes fall below the cutoff and are dropped",
    B:"結果更準確", B_en:"More accurate results",
    C:"跑得更慢", C_en:"Slower run",
    D:"沒有差別", D_en:"No difference",
    ans:"A",
    exp:"10x 每顆細胞分子數少一個量級，cutoff 應為 0.1；用 1 會丟掉幾乎所有基因。",
    exp_en:"10x has an order of magnitude fewer molecules per cell; the cutoff should be 0.1. Using 1 drops nearly every gene." },
  { type:"single",
    stem:"CellChat 的 netVisual_circle 顯示巨噬細胞 → 惡性細胞的邊「互動數」最多，但「互動強度」最粗的是惡性 → 內皮。該先追哪一條？",
    stem_en:"CellChat's netVisual_circle shows the most interaction pairs for macrophage → malignant, but the thickest weight for malignant → endothelial. Which to chase first?",
    A:"互動數最多的那條", A_en:"The one with the most pairs",
    B:"強度最粗的那條，再回頭看它由幾對 L–R 組成", B_en:"The thickest weight, then check how many L–R pairs compose it",
    C:"兩條一樣重要", C_en:"Both equally",
    D:"看 p 值最小的", D_en:"The smallest p value",
    ans:"B",
    exp:"對數多不代表強；先看 weight 找主軸，再回 count 圖與 contribution 看組成。",
    exp_en:"Many pairs ≠ strong; find the main axis by weight, then return to counts and contribution for composition." },
  { type:"single",
    stem:"你把四位病人的核心樣本合併成一個 Seurat 物件跑 CellChat，得到很多顯著的配體受體對。最大的問題是？",
    stem_en:"You merged four patients' core samples into one Seurat object and ran CellChat, getting many significant pairs. The biggest problem?",
    A:"細胞太多跑太慢", A_en:"Too many cells, too slow",
    B:"配體與受體可能來自不同病人的細胞——它們不可能真的對話；要每個樣本分開跑", B_en:"Ligand and receptor may come from different patients' cells — they cannot actually talk; run per sample",
    C:"應該用 counts 層", C_en:"Should have used the counts layer",
    D:"沒有問題", D_en:"No problem",
    ans:"B",
    exp:"通訊只能發生在同一個樣本內；合併跑會製造假的配對。每樣本各跑一次，再比較四位病人一致的路徑。",
    exp_en:"Communication happens only within a sample; pooling fabricates pairs. Run per sample, then compare pathways consistent across patients." },
  { type:"single",
    stem:"你的 pseudobulk 火山圖所有點擠成一根直柱，log2FC 幾乎都是 0.2 左右，但 padj 很小。最可能的原因是？",
    stem_en:"Your pseudobulk volcano is a single vertical bar: nearly every log2FC sits near 0.2, yet padj is tiny. Most likely cause?",
    A:"DESeq2 沒收斂", A_en:"DESeq2 failed to converge",
    B:"樣本只有 8 個時 apeglm 的先驗太強，把幾乎所有 LFC 壓成同一值；火山圖改用未收縮 LFC，效應量改用 ashr", B_en:"With 8 samples the apeglm prior dominates and squeezes nearly every LFC to one value; plot the raw LFC and report ashr",
    C:"基因太多，應該先篩到 2,000 個", C_en:"Too many genes; filter to 2,000 first",
    D:"應該用 cell-level Wilcoxon", D_en:"Use cell-level Wilcoxon instead",
    ans:"B",
    exp:"收縮太強是小 n 的典型症狀。GSEA 的排序也會因此全是同分而跑不完——改用 Wald stat 排序。",
    exp_en:"Over-shrinkage is the classic small-n symptom. GSEA ranks become all ties and never finish — rank by the Wald stat instead." },
  { type:"single",
    stem:"用 clusterProfiler 做 GO ORA 時，universe 留空與設成「被檢定的基因」相比，結果通常會？",
    stem_en:"In clusterProfiler GO ORA, leaving universe empty versus setting it to the tested genes usually gives?",
    A:"完全一樣", A_en:"Identical results",
    B:"顯著詞條變少", B_en:"Fewer significant terms",
    C:"顯著詞條大幅變多，多數是假的——因為單細胞只測到一萬多個基因，用全基因組當背景每個詞條都膨脹", C_en:"Many more significant terms, mostly spurious — single cell detects ten-odd thousand genes, and a whole-genome background inflates every term",
    D:"只影響 KEGG 不影響 GO", D_en:"Affects KEGG only, not GO",
    ans:"C",
    exp:"背景必須是進了 DESeq2 的那些基因。GSEA 沒有這個坑，因為它的背景自動是排序清單本身。",
    exp_en:"The background must be the genes that entered DESeq2. GSEA avoids this trap since its background is the ranked list itself." },
],

}};

const labels_en = {
  "Q1：觀念篇": "Q1: Concepts",
  "Q2：實作篇 I": "Q2: Hands-on I",
  "Q3：實作篇 II": "Q3: Hands-on II",
};
